require('fs').mkdirSync('test-results',{recursive:true});
const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:1440,height:900}}),results=[],errors=[];const test=(name,pass,detail)=>{results.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,detail||'')};p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:8765/?qa');await p.waitForFunction(()=>__qa?.modelCache.size===7);
await p.click('#fullscreenBtn');await p.waitForFunction(()=>!!document.fullscreenElement);test('全屏按钮实际进入浏览器全屏',await p.evaluate(()=>document.fullscreenElement===document.documentElement));await p.keyboard.press('f');await p.waitForFunction(()=>!document.fullscreenElement);test('F 快捷键退出全屏',await p.locator('#fullscreenBtn').getAttribute('aria-pressed')==='false');
await p.click('#researchBtn');test('局外研究显示 10 条路线',await p.locator('#shop .researchItem').count()===10);await p.evaluate(()=>{__qa.getMeta().coins=10000;document.querySelector('#researchClose').click();document.querySelector('#researchBtn').click()});await p.locator('[data-research=haste]').click();test('点击购买研究扣费且等级提升',await p.evaluate(()=>__qa.getMeta().up.haste===1&&__qa.getMeta().coins===9910));await p.screenshot({path:'test-results/v6-research.png'});await p.reload();await p.waitForFunction(()=>__qa?.modelCache.size===7);test('研究购买持久保存',await p.evaluate(()=>__qa.getMeta().up.haste===1));
const migration=await p.evaluate(()=>{const q=__qa,old=localStorage.getItem('voidstorm_meta_v1');localStorage.setItem('voidstorm_meta_v1',JSON.stringify({coins:1234,up:{power:5,hp:3,speed:2,magnet:1},runs:8}));const m=q.loadMeta();localStorage.setItem('voidstorm_meta_v1',old);return {valid:m.coins===1234&&m.up.power===5&&m.up.haste===0&&Object.keys(m.up).length===10,runs:m.runs}});test('旧版四项研究存档无损迁移',migration.valid&&migration.runs===8);
await p.click('#startBtn');await p.waitForFunction(()=>__qa.state.running);const logic=await p.evaluate(()=>{const q=__qa,s=q.state,h=s.hero,T=q.THREE,out=[],test=(name,pass,detail)=>out.push({name,pass:!!pass,detail});s.paused=true;const meta=q.getMeta(),saved={...meta.up};for(const id of Object.keys(q.RESEARCH))meta.up[id]=10;const d=q.derivedHero(q.CHARS.vanguard);test('十条研究均影响真实属性或 R 充能',d.maxHp>200&&d.speed>9&&d.power>1.4&&d.haste===.8&&d.armor===.15&&d.crit===.2&&d.regen===.008&&d.xpGain===1.3&&d.magnet>5);meta.up=saved;q.refreshDerived();test('局外研究禁止战斗中购买',!q.buyResearch('power'));test('战斗技能与属性卡池均精简为 8 种',Object.keys(q.WEAPONS).length===8&&Object.keys(q.PASSIVES).length===8);test('所有属性最高 Lv3',Object.values(q.PASSIVES).every(d=>d.max===3));
s.weapons={pulse:{lv:5,evo:false},blade:{lv:5,evo:false}};s.passives={haste:3,move:3};document.querySelector('#levelModal').classList.remove('hidden');q.selectChoice({kind:'passive',id:'haste'});test('即使旧卡片再次触发也不能升到 Lv4',s.passives.haste===3);document.querySelector('#levelModal').classList.add('hidden');let clean=true,ready=true;for(let i=0;i<200;i++){const cs=q.buildChoices();clean&&=!cs.some(c=>c.kind==='passive'&&['haste','move'].includes(c.id));ready&&=cs.some(c=>c.kind==='evo')}test('200 轮：3/3 属性不再出现',clean);test('满足条件的进化卡每轮优先提供',ready);s.weapons.pulse.evo=true;s.weapons.blade.evo=true;test('已进化技能从卡池移除',!q.buildChoices().some(c=>['pulse','blade'].includes(c.id)));
s.weapons={pulse:{lv:1,evo:false},blade:{lv:1,evo:false},mine:{lv:1,evo:false},chain:{lv:1,evo:false},orbital:{lv:1,evo:false}};s.passives={power:3,haste:3,area:3,armor:3,magnet:3,maxhp:3};const eligible=q.replaceablePassive();test('满属性槽时找到不参与当前进化的置换目标',['area','armor','magnet'].includes(eligible));let replacement=null;for(let i=0;i<100&&!replacement;i++)replacement=q.buildChoices().find(c=>c.replace);test('满槽仍可出现缺失的配套属性',!!replacement);if(replacement){document.querySelector('#levelModal').classList.remove('hidden');q.selectChoice(replacement);test('置换只替换一个属性，槽位保持六个',Object.keys(s.passives).length===6&&s.passives[replacement.id]===1&&!s.passives[replacement.replace])}s.paused=true;
// Complete an actual evolving build through 100 level choices; check every offer and resulting state.
s.weapons={pulse:{lv:1,timer:0,evo:false}};s.passives={};s.level=1;s.xp=0;s.xpNeed=12;s.evolutions=0;let legal=true,noOverflow=true;for(let level=2;level<=101;level++){s.level=level;s.paused=true;document.querySelector('#levelModal').classList.remove('hidden');const cs=q.buildChoices();legal&&=cs.length===3&&new Set(cs.map(c=>c.id)).size===3&&cs.every(c=>c.kind!=='passive'||(s.passives[c.id]||0)<3);const best=cs.find(c=>c.kind==='evo')||cs.find(c=>c.kind==='weapon'&&s.weapons[c.id])||cs.find(c=>c.kind==='passive'&&Object.keys(s.weapons).some(id=>q.WEAPONS[id].pair===c.id))||cs[0];q.selectChoice(best);noOverflow&&=Object.values(s.passives).every(lv=>lv<=3)&&Object.values(s.weapons).every(w=>w.lv<=5)&&Object.keys(s.passives).length<=6&&Object.keys(s.weapons).length<=5}test('100 次实际选择：属性从不超过 3/3、技能不超过 Lv5',legal&&noOverflow);test('后期构筑能实际完成进化',s.evolutions>=3,{evolutions:s.evolutions,weapons:structuredClone(s.weapons),passives:structuredClone(s.passives)});s.passives.haste=5;test('旧的高等级状态显示进度仍封顶 3/3',!q.evolutionRow('pulse').includes('5/3'));s.paused=true;
function cleanScene(){for(const arr of ['enemies','projectiles','enemyProjectiles','gems','zones','fx','pickups']){s[arr].forEach(o=>q.removeObject(o.mesh));s[arr]=[]}s.boss=null;s.victory=false;s.bossKilled=false;s.bossStarted=false;s.ultSequence=null;h.barrier=null;h.shield=0;h.invuln=999;h.hp=h.maxHp;h.mesh.position.set(0,0,0)}
for(const kind of Object.keys(q.BOSS_ARCHETYPES)){cleanScene();const boss=q.spawnEnemy('boss',true,true,15,kind);boss.mesh.position.set(0,0,0);h.mesh.position.set(0,0,12);test(kind+' 首领具有独立模型、名称、血量',boss.archetype===kind&&boss.maxHp>5000&&!!boss.crown&&document.querySelector('#bossName').textContent===q.BOSS_ARCHETYPES[kind].name);q.bossPattern(boss);const first=boss.combo.steps[0];test(kind+' 第一段只产生预警',s.enemyProjectiles.length===0&&s.fx.some(f=>f.bossHazard)&&boss.combo.index===1);q.advanceBossCombo(boss,2.16);test(kind+' 连招第二段具有新预警',boss.combo.index===2&&boss.warning.name.includes('2/3'));q.advanceBossCombo(boss,2.16);test(kind+' 连招第三段存在',boss.combo.index===3);q.advanceBossCombo(boss,2.16);test(kind+' 连招结束留出输出间隙',!boss.combo&&boss.shoot>=3);boss.hp=boss.maxHp*.4;q.bossPattern(boss);test(kind+' 半血升级四段连招',boss.combo.steps.length===4);q.killEnemy(boss);q.updateFX(3);test(kind+' 死亡取消未落地的攻击',s.enemyProjectiles.length===0);}
cleanScene();const boss=q.spawnEnemy('boss',true,true,15,'siege');boss.mesh.position.set(0,0,0);h.mesh.position.set(0,0,4);h.invuln=0;h.shield=0;h.hp=h.maxHp;q.bossPattern(boss);const before=h.hp;q.updateFX(1);test('连招重锤预警期间无伤害',h.hp===before);h.mesh.position.set(9,0,0);q.updateFX(.56);test('走出重锤预警可以躲避',h.hp===before);q.advanceBossCombo(boss,2.16);h.mesh.position.set(0,0,-12);q.updateFX(1.56);test('连招三线向锁定方向发射，反侧安全',h.hp===before);
cleanScene();s.level=6;s.weapons={pulse:{lv:5,evo:true,timer:0},sentinel:{lv:4,evo:false,timer:0},chain:{lv:3,evo:false,timer:0}};s.passives={haste:3,maxhp:3,power:2};q.refreshDerived();h.skillCd=0;h.coreTime=0;s.paused=false;q.useSkill();test('保留 E 壁垒与拦截状态',!!h.barrier);h.invuln=0;q.hitHero(10);test('E 仍累计吸收用于反击',h.barrier.absorbed===10);for(let i=0;i<65;i++)q.updateDefense(.05);test('E 结束有多层冲击特效且状态释放',!h.barrier&&s.fx.some(f=>f.max===.6));s.charge=100;q.useUlt();for(let i=0;i<75;i++)q.updateSkillSequence(.05);test('R 终末冲击增强且序列正常结束',!s.ultSequence&&s.fx.some(f=>f.max===.6));h.coreKills=11;const drone=q.spawnEnemy('drone',false,false,5);q.killEnemy(drone);test('保留角色 12 击杀被动',h.coreKills===0&&h.coreTime===4);s.paused=true;q.updateHUD(true);return out});for(const r of logic)test(r.name,r.pass,r.detail);
await p.evaluate(()=>{__qa.openGuide()});await p.screenshot({path:'test-results/v6-guide.png'});test('进化图谱只显示 8 套配方',await p.locator('#evolutionList .evoRecipe').count()===8);await p.click('#guideClose');await p.evaluate(()=>{const q=__qa,s=q.state;s.paused=false;s.weapons={pulse:{lv:5,evo:false,timer:0},mine:{lv:3,evo:false,timer:0}};s.passives={haste:3,power:2};q.addXp(s.xpNeed)});await p.screenshot({path:'test-results/v6-cards.png'});test('真实卡片呈现进化选项，没有 4/3',await p.locator('#choices .evo').count()>0&&!((await p.locator('#choices').innerText()).includes('4/3')));
await p.evaluate(()=>{const q=__qa,s=q.state;document.querySelector('#levelModal').classList.add('hidden');s.paused=true;for(const arr of ['enemies','fx','projectiles','enemyProjectiles','zones']){s[arr].forEach(o=>q.removeObject(o.mesh));s[arr]=[]}s.hero.mesh.position.set(0,0,8);const boss=q.spawnEnemy('boss',true,true,15,'prism');boss.mesh.position.set(0,0,-4);s.bossStarted=true;q.bossPattern(boss);q.updateFX(.35);q.updateHero(0);q.updateHUD(true);q.renderer.render(q.scene,q.camera)});await p.screenshot({path:'test-results/v6-boss-prism.png'});
test('无控制台与运行错误',errors.length===0,errors);fs.writeFileSync('test-results/v6-results.json',JSON.stringify(results,null,2));await b.close();if(results.some(r=>!r.pass))process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
