require('fs').mkdirSync('test-results',{recursive:true});
const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),rows=[],errors=[];const test=(name,pass,detail)=>rows.push({name,pass:!!pass,detail});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/?qa');await p.waitForFunction(()=>__qa?.modelCache.size===7);await p.tap('#fullscreenBtn');await p.waitForFunction(()=>!!document.fullscreenElement);test('触屏全屏按钮真实生效',await p.evaluate(()=>!!document.fullscreenElement));await p.tap('#fullscreenBtn');await p.waitForFunction(()=>!document.fullscreenElement);
await p.tap('#researchBtn');test('手机研究面板无横向溢出',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'test-results/v6-mobile-research.png'});await p.locator('[data-research=charge]').scrollIntoViewIfNeeded();test('第十条局外研究可以滚动查看',await p.locator('[data-research=charge]').isVisible());await p.tap('#researchClose');await p.tap('#startBtn');await p.waitForFunction(()=>__qa.state.running);await p.evaluate(()=>{__qa.state.hero.invuln=999;__qa.state.level=6;__qa.state.charge=100});await p.tap('#eBtn');test('手机 E 屏障可释放',await p.evaluate(()=>!!__qa.state.hero.barrier));await p.tap('#rBtn');test('手机 R 阵列可释放',await p.evaluate(()=>!!__qa.state.ultSequence));await p.evaluate(()=>__qa.state.paused=true);await p.screenshot({path:'test-results/v6-mobile-effects.png'});await p.evaluate(()=>{__qa.state.paused=false;__qa.addXp(__qa.state.xpNeed)});await p.tap('#levelGuideBtn');test('手机图谱显示 8 套配方',await p.locator('#evolutionList .evoRecipe').count()===8);await p.screenshot({path:'test-results/v6-mobile-guide.png'});await p.tap('#guideClose');await p.locator('#choices button').nth(2).tap();test('竖屏第三张卡可选',await p.evaluate(()=>!__qa.state.paused));
await p.setViewportSize({width:844,height:390});await p.evaluate(()=>{__qa.state.paused=false;__qa.addXp(__qa.state.xpNeed)});await p.screenshot({path:'test-results/v6-landscape-cards.png'});await p.tap('#levelGuideBtn');await p.tap('#guideClose');await p.locator('#choices button').nth(2).tap();test('横屏卡牌和图谱可操作',await p.evaluate(()=>!__qa.state.paused&&document.documentElement.scrollWidth<=innerWidth));
const extra=await p.evaluate(()=>{const q=__qa,s=q.state,h=s.hero,T=q.THREE,out=[],test=(name,pass,detail)=>out.push({name,pass:!!pass,detail});s.paused=true;function clean(){for(const arr of ['enemies','fx','projectiles','enemyProjectiles','zones','gems','pickups']){s[arr].forEach(o=>q.removeObject(o.mesh));s[arr]=[]}s.ultSequence=null;h.barrier=null;s.victory=false;s.boss=null;s.bossStarted=false;s.victoryAt=null;h.hp=h.maxHp;h.invuln=999;h.mesh.position.set(0,0,0)}clean();q.renderer.render(q.scene,q.camera);const base=q.renderer.info.memory.geometries,counts=[];
for(let i=0;i<5;i++){s.paused=false;h.skillCd=0;s.charge=100;q.useSkill();q.useUlt();for(let t=0;t<100;t++){q.updateDefense(.05);q.updateSkillSequence(.05);q.updateFX(.05)}q.renderer.render(q.scene,q.camera);counts.push(q.renderer.info.memory.geometries)}test('新版强化特效连续释放后资源回收稳定',counts.every(n=>n<=base+2),{base,counts});
clean();for(const kind of Object.keys(q.BOSS_ARCHETYPES)){const e=q.spawnEnemy('boss',true,true,15,kind);e.mesh.position.set(0,0,0);h.mesh.position.set(0,0,12);s.paused=false;q.bossPattern(e);s.paused=true;let indices=new Set();for(let i=0;i<180;i++){if(e.combo)indices.add(e.combo.index);q.updateEnemies(.05);q.updateProjectiles(.05);q.updateFX(.05)}test(kind+' 连招经过实际敌人更新循环执行',indices.has(1)&&indices.has(2)&&indices.has(3));clean()}
const boss=q.spawnEnemy('boss',true,true,15,'tempest');boss.mesh.position.set(0,0,0);h.mesh.position.set(0,0,12);q.bossPattern(boss);q.updateFX(1.56);test('风暴主宰弹幕保留可见安全扇区',s.enemyProjectiles.length>10&&s.enemyProjectiles.every(p=>Math.abs(Math.atan2(p.vel.x,p.vel.z))>=.52));boss.hp=boss.maxHp*.4;q.updateEnemies(.05);test('半血过载只触发一次并强化核心旋转',boss.enraged&&s.fx.some(f=>f.max===.6));
clean();s.charge=0;const meta=q.getMeta(),old=meta.up.charge;meta.up.charge=0;q.killEnemy(q.spawnEnemy('drone',false,false,6));const normal=s.charge;s.charge=0;meta.up.charge=10;q.killEnemy(q.spawnEnemy('drone',false,false,6));test('蓄电池研究实际增加 R 击杀充能 50%',Math.abs(s.charge/normal-1.5)<.001);meta.up.charge=old;
clean();s.paused=true;h.mesh.position.set(0,0,8);const e=q.spawnEnemy('boss',true,true,15,'tempest');e.mesh.position.set(0,0,-5);s.bossStarted=true;q.bossPattern(e);q.updateFX(.2);q.updateHUD(true);q.updateHero(0);return out});rows.push(...extra);
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>__qa.renderer.render(__qa.scene,__qa.camera));await p.screenshot({path:'test-results/v6-mobile-boss.png'});test('手机 Boss HUD 不遮挡全屏与技能按钮',await p.evaluate(()=>{const a=document.querySelector('#bossWrap').getBoundingClientRect(),e=document.querySelector('#eBtn').getBoundingClientRect(),f=document.querySelector('#fullscreenBtn').getBoundingClientRect();return a.bottom<e.top&&a.bottom<f.top}));
// Exercise unsupported API branch without pretending that it is native full screen.
await p.evaluate(()=>{Object.defineProperty(document.documentElement,'requestFullscreen',{value:undefined,configurable:true});Object.defineProperty(document.documentElement,'webkitRequestFullscreen',{value:undefined,configurable:true})});await p.tap('#fullscreenBtn');test('不支持全屏时明确提示，没有假全屏状态',await p.evaluate(()=>!document.fullscreenElement&&document.querySelector('#toast').textContent.includes('不支持页面全屏')));test('手机新增功能零运行错误',errors.length===0,errors);fs.writeFileSync('test-results/v6-mobile-results.json',JSON.stringify(rows,null,2));console.log(rows);await b.close();if(rows.some(r=>!r.pass))process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
