require('fs').mkdirSync('test-results',{recursive:true});
const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
const root=path.resolve('.');const results=[];const errors=[];const warnings=[];const check=(name,ok,detail)=>{results.push({name,pass:!!ok,detail});console.log(ok?'PASS':'FAIL',name,detail??'');if(!ok)process.exitCode=1};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
async function pageFor(options={}){const ctx=await browser.newContext(options);const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning'&&!m.text().includes('GPU stall'))warnings.push(m.text())});return p}
const p=await pageFor({viewport:{width:1440,height:900}});await p.goto('http://127.0.0.1:8765/?qa');await p.waitForFunction(()=>window.__qa?.modelCache.size===7);await p.screenshot({path:'test-results/qa-menu.png'});await p.click('#startBtn');await p.waitForFunction(()=>__qa.state.running);await p.evaluate(()=>{__qa.state.hero.invuln=999});await p.keyboard.down('KeyD');await p.waitForFunction(()=>__qa.state.hero.mesh.position.x>.5,{},{timeout:8000});await p.keyboard.up('KeyD');
check('键盘实际移动',await p.evaluate(()=>__qa.state.hero.mesh.position.x>0.5));
check('加载全部本地模型',await p.evaluate(()=>[...__qa.modelCache.values()].every(Boolean)));
await p.click('#pauseBtn');const pauseTime=await p.evaluate(()=>__qa.state.time);await p.waitForTimeout(300);check('暂停冻结游戏时钟',await p.evaluate(t=>__qa.state.time===t,pauseTime));await p.click('#resumeBtn');await p.waitForFunction(t=>__qa.state.time>t,pauseTime,{timeout:8000});check('恢复任务',await p.evaluate(t=>__qa.state.time>t,pauseTime));
const logic=await p.evaluate(()=>{const q=__qa,s=q.state,T=q.THREE,out=[];const test=(n,v,d)=>out.push({name:n,pass:!!v,detail:d});s.paused=true;
const sizes=[];for(const id of ['drone','alien','gunner','boss']){const e=q.spawnEnemy(id,false,id==='boss',5);e.mesh.updateMatrixWorld(true);const b=new T.Box3().setFromObject(e.mesh.children[0],true),size=b.getSize(new T.Vector3());sizes.push({id,size:size.toArray()});test(id+' 实际模型尺寸可见',Math.max(...size.toArray())>1.5&&Math.max(...size.toArray())<12,size.toArray());}
const pos=s.hero.mesh.position.clone(),cameraQ=q.camera.quaternion.clone(),height=q.camera.position.y;s.hero.mesh.position.add(new T.Vector3(2,0,3));q.updateHero(0);test('镜头只跟随 X/Z，角度高度不变',Math.abs(q.camera.position.y-height)<1e-9&&q.camera.quaternion.angleTo(cameraQ)<1e-7);s.hero.mesh.position.copy(pos);q.updateHero(0);
const victim=s.enemies.find(e=>!e.boss);victim.hp=1000;const oldPos=victim.mesh.position.clone(),fx=s.fx.length;q.damageEnemy(victim,10,false);test('受击白闪、粒子、击退、数字',victim.hitVisual&&s.fx.length>fx&&victim.mesh.position.distanceTo(oldPos)>.05&&document.querySelectorAll('.dmg').length>0);q.updateEnemies(.2);test('受击材质恢复',!victim.hitVisual);const gems=s.gems.length;q.killEnemy(victim);test('死亡爆炸并产生经验',victim.dead&&s.gems.length===gems+1);
s.paused=false;s.hero.hp=1;s.xp=0;s.xpNeed=12;s.level=1;q.addXp(70);const lv=s.level;q.addXp(10);test('同帧经验不跳过卡牌',s.level===lv&&s.paused&&document.querySelectorAll('#choices .choice').length===3);test('升级立即恢复满血',s.hero.hp===s.hero.maxHp);document.querySelector('#choices button').click();test('多级经验逐次选择',s.level===lv+1&&s.paused);let safety=0;while(s.paused&&safety++<10)document.querySelector('#choices button').click();
s.level=2;s.hero.skillCd=0;const start=s.hero.mesh.position.clone();q.useSkill();test('Lv2 锁定 E',s.hero.mesh.position.distanceTo(start)===0);s.level=3;s.aim.set(1,0,0);q.useSkill();test('Lv3 E 壁垒、护盾、CD，无位移',s.hero.mesh.position.distanceTo(start)===0&&s.hero.shield>0&&s.hero.skillCd>0&&!!s.hero.barrier);const at=s.hero.mesh.position.clone();q.useSkill();test('E 冷却中不能连放',s.hero.mesh.position.distanceTo(at)===0);
s.level=5;s.charge=100;q.useUlt();test('Lv5 锁定 R',!s.ultSequence&&s.charge===100);s.level=6;q.useUlt();test('Lv6 R 消耗充能与离子阵列',s.charge===0&&!!s.ultSequence);for(let i=0;i<80;i++)q.updateSkillSequence(.05);test('R 连射及终端冲击结束',!s.ultSequence);
s.paused=true;const available=Object.keys(q.WEAPONS);s.weapons=Object.fromEntries(available.slice(0,5).map(id=>[id,{lv:5,timer:1,evo:false}]));s.passives=Object.fromEntries(Object.keys(q.PASSIVES).slice(0,6).map(id=>[id,5]));let capOK=true,evoOK=true;for(let i=0;i<150;i++){const choices=q.buildChoices();capOK&&=choices.length===3&&!choices.some(c=>c.newCard);evoOK&&=choices.filter(c=>c.kind==='evo').every(c=>s.weapons[c.id].lv===5&&s.passives[q.WEAPONS[c.id].pair]>=3)}test('150 次抽卡：5 技能/6 属性上限与 Lv5 上限',capOK);test('进化卡仅在技能与属性满足时出现',evoOK);
s.weapons=Object.fromEntries(available.slice(0,5).map(id=>[id,{lv:5,timer:1,evo:true}]));s.passives=Object.fromEntries(Object.keys(q.PASSIVES).slice(0,6).map(id=>[id,5]));const utilities=q.buildChoices();test('构筑全满仍有三张互异战术卡',utilities.length===3&&new Set(utilities.map(c=>c.id)).size===3&&utilities.every(c=>c.kind==='utility'));
// each real weapon branch must create a visible effect or projectile, and damage actual enemies.
s.hero.mesh.position.set(0,0,0);s.enemies.forEach(e=>q.removeObject(e.mesh));s.enemies=[];for(let i=0;i<8;i++){const e=q.spawnEnemy('drone',false,false,3);e.mesh.position.set(Math.cos(i/8*6.28)*3,0,Math.sin(i/8*6.28)*3);e.hp=e.maxHp=100000}q.refreshDerived();s.hero.power=1;s.hero.area=1;s.hero.projectiles=1;s.hero.haste=1;s.hero.duration=1;s.hero.crit=0;s.hero.invuln=999;s.paused=true;for(const id of available){for(const arr of [s.projectiles,s.fx,s.zones]){for(const item of arr)q.removeObject(item.mesh);arr.length=0}const before=s.enemies.reduce((sum,e)=>sum+e.hp,0);q.fireWeapon(id,{lv:5,evo:true,timer:0});const visible=s.projectiles.length+s.fx.length+s.zones.length;for(let i=0;i<75;i++){q.updateProjectiles(.05);q.updateZones(.05);q.updateFX(.05)}test('技能机制 '+id,visible>0&&s.enemies.reduce((sum,e)=>sum+e.hp,0)<before,{visible,damage:before-s.enemies.reduce((sum,e)=>sum+e.hp,0)})}
s.weapons={pulse:{lv:1,timer:1,evo:false},sentinel:{lv:2,timer:1,evo:false}};q.updateCompanions(.1);test('无人机实体存在',q.scene.children.some(o=>o.type==='Group'&&Math.abs(o.position.y-1.7)<.2));
s.gems.forEach(g=>q.removeObject(g.mesh));s.gems=[];q.spawnGem(s.hero.mesh.position.clone().add(new T.Vector3(2.5,0,0)),2);q.updateDrops(.05);const g=s.gems[0];test('经验捕获、加速与拖尾',g?.pull&&g.vel.length()>0&&g.tail.visible);const xp=s.xp;for(let i=0;i<60;i++)q.updateDrops(.016);test('经验吸收结束并结算',s.gems.length===0&&s.xp>xp);
const saved=q.modelCache.get('drone');q.modelCache.set('drone',null);const fallback=q.actorVisual('missing-model',0xff7733,2.75,1);const fb=new T.Box3().setFromObject(fallback.root.children[0],true).getSize(new T.Vector3());test('模型失败显示明显备用机体',!fallback.fromAsset&&fb.length()>2);q.removeObject(fallback.root);q.modelCache.set('drone',saved);
test('高速弹道使用扫掠碰撞',q.segmentDistanceSq(new T.Vector3(-2,0,0),new T.Vector3(2,0,0),new T.Vector3())===0);
s.weapons={pulse:{lv:3,timer:0,evo:false},blade:{lv:2,timer:0,evo:false},chain:{lv:2,timer:0,evo:false},sentinel:{lv:2,timer:0,evo:false},field:{lv:2,timer:0,evo:false}};s.passives={haste:2,maxhp:2,power:1};s.level=6;s.charge=100;s.hero.hp=s.hero.maxHp;s.paused=false;q.updateHUD(true);return out});for(const r of logic)check(r.name,r.pass,r.detail);
await p.waitForTimeout(600);await p.screenshot({path:'test-results/qa-combat.png'});await p.keyboard.press('KeyR');await p.waitForTimeout(180);await p.screenshot({path:'test-results/qa-ult.png'});await p.evaluate(()=>{__qa.state.hero.hp=5;__qa.addXp(__qa.state.xpNeed)});await p.screenshot({path:'test-results/qa-cards.png'});
const mobile=await pageFor({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});await mobile.goto('http://127.0.0.1:8765/?qa');await mobile.waitForFunction(()=>window.__qa?.modelCache.size===7);check('手机机库无横向溢出',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.click('#startBtn');await mobile.waitForFunction(()=>__qa.state.running);await mobile.evaluate(()=>__qa.state.hero.invuln=999);check('触屏自动显示摇杆和技能键',await mobile.locator('#mobile').isVisible());
const joy=await mobile.locator('#moveJoy').boundingBox();const cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:joy.x+56,y:joy.y+56}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:joy.x+88,y:joy.y+56}]});await mobile.waitForFunction(()=>__qa.state.hero.mesh.position.x>.2,{},{timeout:8000});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('手机摇杆输入实际移动',await mobile.evaluate(()=>__qa.state.hero.mesh.position.x>.2));await mobile.screenshot({path:'test-results/qa-mobile.png'});await mobile.click('#pauseBtn');check('手机可以暂停',await mobile.locator('#pauseModal').isVisible());await mobile.click('#resumeBtn');await mobile.evaluate(()=>__qa.addXp(__qa.state.xpNeed));check('手机三张升级卡可选',await mobile.locator('#choices button').count()===3);await mobile.screenshot({path:'test-results/qa-mobile-cards.png'});await mobile.locator('#choices button').nth(1).click();await mobile.setViewportSize({width:844,height:390});await mobile.waitForTimeout(150);await mobile.screenshot({path:'test-results/qa-landscape.png'});check('横屏无页面溢出',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.close();await mobile.close();const offline=await pageFor({viewport:{width:1280,height:800}});let remote=0;offline.on('request',r=>{if(/^https?:/.test(r.url()))remote++});await offline.goto('file://'+root+'/index.html?qa');await offline.waitForFunction(()=>__qa?.modelCache.size===7);await offline.click('#startBtn');await offline.waitForFunction(()=>__qa.state.running);check('双击 HTML 离线运行且零远程请求',remote===0&&await offline.evaluate(()=>__qa.state.hero.fromAsset),await offline.evaluate(()=>({hero:__qa.state.hero.fromAsset,models:[...__qa.modelCache].map(([k,v])=>[k,!!v])})));
check('无 JavaScript / 控制台错误',errors.length===0,errors);check('无应用控制台警告',warnings.length===0,warnings);
fs.writeFileSync('test-results/qa-results.json',JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors,warnings},null,2));await browser.close();console.log('TOTAL',results.length,'FAILED',results.filter(r=>!r.pass).length)})().catch(e=>{console.error(e);process.exitCode=1});
