import {icon} from './icons.js';
import {createWorld,DISTRICTS} from './world.js';
import {originalActor,originalRig,animateOriginal} from './actors.js';

import * as THREE from '../vendor/three/three.module.js';
import { GLTFLoader } from '../vendor/three/loaders/GLTFLoader.js';
import * as SkeletonUtils from '../vendor/three/utils/SkeletonUtils.js';

const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), pick=a=>a[(Math.random()*a.length)|0];
const distSqXZ=(a,b)=>{const dx=a.x-b.x,dz=a.z-b.z;return dx*dx+dz*dz};
const IS_TOUCH=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;document.body.classList.toggle('touch',IS_TOUCH);
const MODEL_URLS={hero:'hero.gltf',drone:'drone.glb',gunner:'gunner.glb',alien:'alien.glb',boss:'boss.glb',crate:'crate.glb',container:'container.glb'};
const ICON={pulse:'▰',blade:'◢',mine:'✹',chain:'ϟ',orbital:'⌖',slicer:'◎',ember:'♨',sentinel:'◆',echo:'◇',field:'◉',vortex:'↻',annihilator:'✦',power:'▲',haste:'»',area:'◯',move:'➤',armor:'⬡',magnet:'⌁',crit:'✧',regen:'+',projectiles:'⋮',duration:'⌛',maxhp:'♥',exp:'XP'};
const CHARS={
 vanguard:{name:'AEGIS-7',role:'AE-12 / 突击型战术机甲',desc:'棱镜壁垒 · 天罚阵列 · 自适应核心',weapon:'pulse',hp:155,speed:7.35,power:1.08,skill:'棱镜壁垒',ult:'离子超载',model:'hero'}
};
const DIFFS={normal:{name:'标准',mul:1,reward:1,desc:'推荐初次任务'},hard:{name:'高压',mul:1.32,reward:1.55,desc:'通关标准后解锁'},nightmare:{name:'湮灭',mul:1.68,reward:2.2,desc:'通关高压后解锁'}};
const PASSIVES={
 power:{name:'聚变增幅器',desc:'伤害 +12%',max:5},haste:{name:'超频核心',desc:'技能/武器冷却 -8%',max:5},area:{name:'空间扩容器',desc:'范围 +10%',max:5},move:{name:'矢量推进器',desc:'移动速度 +7%',max:5},armor:{name:'相位装甲',desc:'受到伤害 -6%',max:5},magnet:{name:'引力回收器',desc:'拾取范围 +18%',max:5},crit:{name:'量子瞄准镜',desc:'暴击率 +6%',max:5},regen:{name:'纳米修复器',desc:'每秒回复 0.35% 最大生命',max:5},projectiles:{name:'并联弹仓',desc:'弹丸/子体数量提高',max:5},duration:{name:'持续协议',desc:'持续型技能时间 +12%',max:5},maxhp:{name:'重型装甲板',desc:'最大生命 +10%',max:5},exp:{name:'战术学习芯片',desc:'经验获取 +10%',max:5}
};
const WEAPONS={
 pulse:{name:'AE-12 能量步枪',icon:'pulse',desc:'高速自动锁定最近目标，连续发射高亮能量弹。',pair:'haste',max:5,evo:'AE-12 零点过载',inspired:'高速追踪弹'},
 blade:{name:'回旋磁刃',icon:'blade',desc:'发射穿透磁刃，飞出后回到机体并再次切割路径。',pair:'move',max:5,evo:'双相回旋刃阵',inspired:'回旋型投射物'},
 mine:{name:'反物质雷环',icon:'mine',desc:'周期性在周围布置延迟爆炸雷体，形成范围清场。',pair:'power',max:5,evo:'深海链爆雷阵',inspired:'定时范围地雷'},
 chain:{name:'雷链矩阵',icon:'chain',desc:'自动向附近敌人释放连锁电弧，在多个目标间跳跃。',pair:'maxhp',max:5,evo:'超导雷暴矩阵',inspired:'连锁闪电'},
 orbital:{name:'轨道打击信标',icon:'orbital',desc:'锁定随机敌群显示预警圈，随后从上方轰击。',pair:'crit',max:5,evo:'天基歼灭阵列',inspired:'随机轨道轰炸'},
 slicer:{name:'旋风切割环',icon:'slicer',desc:'周期性展开环绕机体的高速切割刃，近身击退清场。',pair:'regen',max:5,evo:'六相风暴刃环',inspired:'环绕刀片'},
 ember:{name:'灼热离子矢',icon:'ember',desc:'射出高温弹，命中后留下持续灼烧区域。',pair:'area',max:5,evo:'恒星余烬炮',inspired:'命中留下持续区域'},
 sentinel:{name:'护航无人机',icon:'sentinel',desc:'召唤侧翼无人机定期向最近敌人发射追踪火力。',pair:'duration',max:5,evo:'蜂群护航协议',inspired:'自动召唤物'},
 echo:{name:'回响刃轨',icon:'echo',desc:'向扇面发射穿透刃片，撞到战场边界会反弹。',pair:'projectiles',max:5,evo:'无限回响刃潮',inspired:'反弹穿透弹'},
 field:{name:'近域辐射场',icon:'field',desc:'持续脉冲伤害机体周围敌人，适合贴身防守。',pair:'maxhp',max:5,evo:'零界辐射核心',inspired:'近身伤害光环'},
 vortex:{name:'涡旋脉冲器',icon:'vortex',desc:'旋转释放环形弹幕，形成持续扫荡的螺旋火力。',pair:'regen',max:5,evo:'奇点涡旋炮',inspired:'旋转弹幕'},
 annihilator:{name:'湮灭协议',icon:'annihilator',desc:'长冷却大范围能量清扫，对普通敌人造成巨额伤害。',pair:'exp',max:5,evo:'终末湮灭协议',inspired:'全屏/大范围清场'}
};
const ENEMY_TYPES={
 drone:{hp:28,speed:3.35,dmg:6,rad:.62,color:0xff8055,model:'drone',xp:2,size:2.75},
 alien:{hp:38,speed:2.95,dmg:8,rad:.7,color:0xff7956,model:'alien',xp:3,size:3.05},
 gunner:{hp:55,speed:2.05,dmg:8,rad:.78,color:0xff7654,model:'gunner',xp:4,size:3.25,ranged:true},
 brute:{hp:105,speed:1.75,dmg:13,rad:1.0,color:0xffb357,model:'brute',xp:6,size:3.8},
 boss:{hp:4200,speed:1.42,dmg:24,rad:2.8,color:0xff557c,model:'boss',xp:30,size:10.2,ranged:true}
};
const ACH={first:{name:'第一滴冷却液',test:s=>s.kills>=1},k100:{name:'清扫协议',test:s=>s.kills>=100},lv10:{name:'十级超频',test:s=>s.level>=10},min5:{name:'坚持五分钟',test:s=>s.time>=300},evo:{name:'完成第一次武器进化',test:s=>s.evolutions>=1},elite:{name:'猎杀精英',test:s=>s.elitesKilled>=1},boss:{name:'核心破坏者',test:s=>s.bossKilled},hard:{name:'高压幸存者',test:s=>s.victory&&s.diff==='hard'}};
const META_DEFAULT={coins:0,totalKills:0,runs:0,clears:{normal:0,hard:0,nightmare:0},up:{power:0,hp:0,speed:0,magnet:0},ach:{}};
let meta=loadMeta(), selectedChar='vanguard',selectedDiff='normal';
function loadMeta(){try{const v=JSON.parse(localStorage.getItem('voidstorm_meta_v1')||'null');return Object.assign(structuredClone(META_DEFAULT),v||{}, {clears:Object.assign({},META_DEFAULT.clears,v?.clears||{}),up:Object.assign({},META_DEFAULT.up,v?.up||{}),ach:Object.assign({},v?.ach||{})});}catch{return structuredClone(META_DEFAULT)}}
function saveMeta(){try{localStorage.setItem('voidstorm_meta_v1',JSON.stringify(meta))}catch{showToast('浏览器未允许保存，当前任务仍可继续')}}
function charUnlocked(id){return id==='vanguard'}
function weaponUnlocked(id){return !!WEAPONS[id]}
function diffUnlocked(id){return id==='normal'||(id==='hard'&&meta.clears.normal>0)||(id==='nightmare'&&meta.clears.hard>0)}
function renderMenu(){
 selectedChar='vanguard';if(!diffUnlocked(selectedDiff))selectedDiff='normal';
 const cs=$('#chars');cs.innerHTML='';const c=CHARS.vanguard,b=document.createElement('div');b.className='char selected';b.innerHTML=`<div class="charName">${c.name}</div><div class="charRole">${c.role}</div><div class="charDesc">${c.desc}</div><span class="tag">${WEAPONS[c.weapon].name}</span><span class="tag">E ${c.skill}</span><span class="tag">R ${c.ult}</span><div class="coreMenu">被动 / 自适应核心<br><small>每 12 次击杀：10% 护盾，4 秒内伤害 +15%</small></div>`;cs.appendChild(b);$('#unlockText').textContent='作战就绪 / 01';
 const ds=$('#diffs');ds.innerHTML='';for(const [id,d] of Object.entries(DIFFS)){const lock=!diffUnlocked(id),x=document.createElement('button');x.className='diff '+(id===selectedDiff?'selected ':'')+(lock?'locked':'');x.innerHTML=`<b>${d.name}</b><div class="tiny">${lock?'未解锁':d.desc}</div>`;if(!lock)x.onclick=()=>{selectedDiff=id;renderMenu()};ds.appendChild(x)}
 $('#metaCoins').textContent=meta.coins;$('#metaKills').textContent=meta.totalKills;$('#metaRuns').textContent=meta.runs;$('#metaPower').textContent='战术等级 '+Object.values(meta.up).reduce((a,b)=>a+b,0);
 const shop=$('#shop');shop.innerHTML='';const defs={power:['火控增幅','永久伤害 +4%/级'],hp:['装甲扩容','永久最大生命 +5%/级'],speed:['推进校准','永久移速 +2.5%/级'],magnet:['回收磁场','永久拾取范围 +8%/级']};for(const [id,[n,desc]] of Object.entries(defs)){const lv=meta.up[id],cost=90+lv*90,x=document.createElement('button');x.className='shopBtn';x.innerHTML=`<span><b>${n} · Lv.${lv}/5</b><small>${desc}</small></span><span class="price">${lv>=5?'MAX':cost+' CR'}</span>`;x.disabled=lv>=5;x.onclick=()=>{if(lv<5&&meta.coins>=cost){meta.coins-=cost;meta.up[id]++;saveMeta();renderMenu()}};shop.appendChild(x)}
}
$('#resetBtn').onclick=()=>{if(confirm('确定清空 VOIDSTORM 本地存档？')){meta=structuredClone(META_DEFAULT);saveMeta();renderMenu()}};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x080e14);scene.fog=new THREE.FogExp2(0x101922,.012);
const CAMERA_OFFSET=new THREE.Vector3(0,23.5,21.5),CAMERA_LOOK_Y=1.15;
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,250);camera.position.set(0,10,16);camera.lookAt(0,1,0);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:!IS_TOUCH,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,IS_TOUCH?1.35:1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=!IS_TOUCH;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;$('#game').appendChild(renderer.domElement);window.__voidstormReady=true;}catch(err){console.error(err);throw err}
scene.add(new THREE.HemisphereLight(0xc6dce5,0x0a1018,1.9));const sun=new THREE.DirectionalLight(0xd7e8eb,3.2);sun.position.set(-12,24,8);sun.castShadow=!IS_TOUCH;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const rim=new THREE.PointLight(0x2fffe1,75,35,2);rim.position.set(9,9,-8);scene.add(rim);
const arena=new THREE.Mesh(new THREE.CircleGeometry(47,72),new THREE.MeshStandardMaterial({color:0x151f28,roughness:.8,metalness:.35}));arena.rotation.x=-Math.PI/2;arena.receiveShadow=true;scene.add(arena);
const grid=new THREE.GridHelper(88,22,0x536472,0x405360);grid.position.y=.03;grid.material.opacity=.24;grid.material.transparent=true;scene.add(grid);
const boundary=new THREE.Mesh(new THREE.RingGeometry(45.5,46.2,72),new THREE.MeshBasicMaterial({toneMapped:false,color:0x5b9ab3,transparent:true,opacity:.32,side:THREE.DoubleSide}));boundary.rotation.x=-Math.PI/2;boundary.position.y=.06;scene.add(boundary);
const obstacles=[];grid.visible=false;boundary.visible=false;const world=createWorld(scene,obstacles,IS_TOUCH);

const loader=new GLTFLoader(),modelCache=new Map();let assetLoading=false;
function fallbackActor(kind,color=0x79d9ee){const g=new THREE.Group(),metal=new THREE.MeshStandardMaterial({color,metalness:.72,roughness:.25,emissive:new THREE.Color(color).multiplyScalar(.11)}),dark=new THREE.MeshStandardMaterial({color:0x15232d,metalness:.8,roughness:.28});if(kind==='drone'){const core=new THREE.Mesh(new THREE.OctahedronGeometry(.55),metal);core.position.y=.7;g.add(core);for(const s of [-1,1]){const wing=new THREE.Mesh(new THREE.BoxGeometry(.95,.1,.3),dark);wing.position.set(s*.68,.72,0);g.add(wing)}}else if(kind==='alien'){const body=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,1),metal);body.position.y=.9;body.scale.set(.9,1.3,.75);g.add(body);for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,.8,6),dark);leg.position.set(s*.32,.35,0);g.add(leg)}}else{const torso=new THREE.Mesh(new THREE.BoxGeometry(.9,1.15,.58),metal);torso.position.y=1.3;g.add(torso);const head=new THREE.Mesh(new THREE.BoxGeometry(.58,.48,.52),dark);head.position.y=2.08;g.add(head);for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.25,.9,.28),dark);leg.position.set(s*.25,.46,0);g.add(leg);const arm=new THREE.Mesh(new THREE.BoxGeometry(.22,.82,.24),metal);arm.position.set(s*.62,1.3,0);g.add(arm)}const gun=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,1.25),dark);gun.position.set(.62,1.25,-.72);g.add(gun)}return g}
function normalizeModel(src,target=2){const root=new THREE.Group(),pivot=new THREE.Group(),m=SkeletonUtils.clone(src);pivot.add(m);root.add(pivot);m.updateMatrixWorld(true);m.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update()});const box=new THREE.Box3().setFromObject(m,true),sz=box.getSize(new THREE.Vector3()),scale=target/Math.max(sz.x,sz.y,sz.z,.01);pivot.scale.setScalar(scale);root.updateMatrixWorld(true);box.setFromObject(pivot,true);const center=box.getCenter(new THREE.Vector3());pivot.position.set(-center.x,-box.min.y,-center.z);root.updateMatrixWorld(true);m.traverse(o=>{if(o.isMesh){o.frustumCulled=false;o.geometry=o.geometry.clone();o.castShadow=!IS_TOUCH;o.receiveShadow=true;if(o.material)o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone()}});return root}
function loadModel(id){if(modelCache.has(id))return Promise.resolve(modelCache.get(id));return new Promise(resolve=>{let done=false;const timeout=setTimeout(()=>finish(null),30000);const finish=v=>{if(done)return;done=true;clearTimeout(timeout);modelCache.set(id,v);resolve(v)};const b64=window.VOIDSTORM_MODELS?.[id];if(!b64){finish(null);return}try{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));loader.parse(bytes.buffer,'',g=>{try{const b=new THREE.Box3().setFromObject(g.scene),sz=b.getSize(new THREE.Vector3());let meshes=0;g.scene.traverse(o=>{if(o.isMesh)meshes++});finish(meshes&&Number.isFinite(sz.length())&&sz.length()>.01?{scene:g.scene,animations:g.animations||[]}:null)}catch{finish(null)}},()=>finish(null))}catch{finish(null)}})}
let preloadPromise;
function preloadModels(){if(preloadPromise)return preloadPromise;preloadPromise=(async()=>{const ids=Object.keys(MODEL_URLS),status=$('#assetStatus');status.textContent='机库自检中…';await Promise.all(ids.map(loadModel));const ok=ids.filter(id=>modelCache.get(id)).length;status.className='assetStatus '+(ok===ids.length?'ok':'warn');status.textContent=ok===ids.length?'● 原创机体就绪 · 离线资源已就位':'● 部分资源异常 · 可视备用机体已就位'})();return preloadPromise}
function marker(radius,color,player=false){const m=new THREE.Mesh(new THREE.RingGeometry(radius*.9,radius,48),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:player?.82:.78,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.045;return m}
function visibilityBeacon(size,color){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.9,depthTest:false,depthWrite:false}),core=new THREE.Mesh(new THREE.OctahedronGeometry(.11),mat);core.position.y=Math.max(1.2,size*.64);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,.46,5),mat.clone());stem.position.y=core.position.y-.28;g.add(core,stem);g.renderOrder=9;return g}
function actorVisual(modelId,color,size=2,markRadius=.7,player=false){const data=modelCache.get(modelId);let authored=null;try{authored=originalActor(modelId==='drone'&&player?'escort':modelId)}catch(err){console.warn('Original model fallback',modelId)}const root=authored?normalizeModel(authored,size):data?normalizeModel(data.scene,size):normalizeModel(fallbackActor(modelId,color),size),tint=new THREE.Color(color);root.traverse(o=>{if(!o.isMesh||!o.material)return;o.castShadow=player&&!IS_TOUCH;o.frustumCulled=modelId==='crate'||modelId==='container';const mats=Array.isArray(o.material)?o.material:[o.material];for(const mat of mats){if(mat.color){mat.color.lerp(tint,mat.userData.original?0:player?.48:.3);mat.userData.vsBaseColor=mat.color.clone()}if(mat.emissive){mat.emissive.lerp(tint,mat.userData.original?0:player?.06:.10);mat.userData.vsBaseEmissive=mat.emissive.clone();mat.userData.vsBaseEmissiveIntensity=mat.emissiveIntensity||0;mat.emissiveIntensity=Math.max(mat.emissiveIntensity||0,player?.12:.26)}}});root.add(marker(markRadius,color,player));if(!player)root.add(visibilityBeacon(size,color));return{root,animations:authored?[]:data?.animations||[],fromAsset:!!authored||!!data,original:!!authored}}
function makeMixer(root,clips){const rig=originalRig(root);if(rig)return rig;if(!clips?.length)return null;const mixer=new THREE.AnimationMixer(root),find=(r)=>clips.find(c=>r.test(c.name));const defs={idle:find(/idle/i)||clips[0],run:find(/run|walk/i),attack:find(/shoot|attack|fire/i),hit:find(/hit|react|damage/i)};const actions={};for(const [k,c] of Object.entries(defs))if(c){actions[k]=mixer.clipAction(c);actions[k].enabled=true}if(actions.idle)actions.idle.play();return{mixer,actions,current:actions.idle?'idle':null,attackUntil:0,hitUntil:0}}
function playAnim(anim,name,fade=.12){if(!anim?.actions?.[name]||anim.current===name)return;const prev=anim.actions[anim.current],next=anim.actions[name];prev?.fadeOut(fade);next.reset().fadeIn(fade).play();anim.current=name}
function updateAnim(anim,dt,moving=false){if(!anim)return;if(anim.procedural){animateOriginal(anim,dt,moving,state.time);return}anim.mixer.update(dt);if(state.time<anim.hitUntil)playAnim(anim,'hit');else if(state.time<anim.attackUntil)playAnim(anim,'attack');else if(moving&&anim.actions.run)playAnim(anim,'run');else playAnim(anim,'idle')}
function syncCamera(){if(!state.hero)return;const p=state.hero.mesh.position;camera.position.set(p.x+CAMERA_OFFSET.x,CAMERA_OFFSET.y,p.z+CAMERA_OFFSET.z);camera.lookAt(p.x,CAMERA_LOOK_Y,p.z)}


function removeObject(obj){if(!obj)return;scene.remove(obj);obj.traverse(o=>{o.geometry?.dispose();if(o.isInstancedMesh)o.dispose();if(o.isSkinnedMesh)o.skeleton?.dispose();if(o.material)for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.dispose()})}
let hangarActor=null;
async function prepareHangar(){await preloadModels();const vis=actorVisual('hero',0x71efff,5.3,1.2,true);hangarActor=vis.root;hangarActor.position.set(-3.3,0,0);hangarActor.rotation.y=.4;scene.add(hangarActor)}

const state={running:false,paused:false,hero:null,enemies:[],projectiles:[],enemyProjectiles:[],gems:[],pickups:[],zones:[],fx:[],weapons:{},passives:{},time:0,kills:0,level:1,xp:0,xpNeed:12,coins:0,charge:0,diff:'normal',char:'vanguard',wave:0,spawnAcc:0,lastElite:0,lastChest:0,lastEvent:0,eventCount:0,evolutions:0,elitesKilled:0,boss:null,bossStarted:false,bossKilled:false,victory:false,minibossStage:0,newAchievements:[],questKills:false,questEvents:false,questEvo:false,manualAim:false,aim:new THREE.Vector3(0,0,-1),bonusPower:1,pendingUnlock:null,ultSequence:null,victoryAt:null};
const key={},mouse={x:0,y:0};let moveTouch=new THREE.Vector2(),aimTouch=new THREE.Vector2(),clock=new THREE.Clock(),lastFrame=performance.now();
addEventListener('keydown',e=>{key[e.code]=true;if(e.code==='KeyE')useSkill();if(e.code==='KeyR')useUlt();if(e.code==='KeyT'){state.manualAim=!state.manualAim;updateAimLabel()}if(e.code==='Escape'){if(!$('#evolutionModal').classList.contains('hidden')){closeGuide();return}if(state.running&&!$('#levelModal').classList.contains('hidden'))return;if(state.running)togglePause()}});addEventListener('keyup',e=>key[e.code]=false);addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function setupJoy(el,vec){let pid=null;const reset=()=>{pid=null;vec.set(0,0);el.style.setProperty('--jx','0px');el.style.setProperty('--jy','0px')};el.addEventListener('pointerdown',e=>{pid=e.pointerId;el.setPointerCapture(pid)});el.addEventListener('pointermove',e=>{if(e.pointerId!==pid)return;const r=el.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),l=Math.hypot(x,y),m=36,k=l>m?m/l:1;vec.set(x*k/m,y*k/m);el.style.setProperty('--jx',x*k+'px');el.style.setProperty('--jy',y*k+'px')});el.addEventListener('pointerup',reset);el.addEventListener('pointercancel',reset)}
setupJoy($('#moveJoy'),moveTouch);setupJoy($('#aimJoy'),aimTouch);$('#eBtn').onclick=useSkill;$('#rBtn').onclick=useUlt;$('#autoBtn').onclick=()=>{state.manualAim=!state.manualAim;updateAimLabel()};

function resetSceneObjects(){for(const c of companions)removeObject(c);companions=[];for(const arr of [state.enemies,state.projectiles,state.enemyProjectiles,state.gems,state.pickups,state.zones,state.fx])for(const o of arr)if(o.mesh)removeObject(o.mesh);if(state.hero?.mesh)removeObject(state.hero.mesh);state.enemies=[];state.projectiles=[];state.enemyProjectiles=[];state.gems=[];state.pickups=[];state.zones=[];state.fx=[];state.boss=null}
function derivedHero(c){return{maxHp:c.hp*(1+meta.up.hp*.05),speed:c.speed*(1+meta.up.speed*.025),power:c.power*(1+meta.up.power*.04),haste:1,area:1,armor:0,magnet:3.2*(1+meta.up.magnet*.08),crit:.05,regen:0,projectiles:1,duration:1,xpGain:1}}
function refreshDerived(){const c=CHARS[state.char],d=derivedHero(c),p=state.passives,h=state.hero;if(!h)return;const oldMax=h.maxHp||d.maxHp;h.maxHp=d.maxHp*(1+(p.maxhp||0)*.10);h.speed=d.speed*(1+(p.move||0)*.07);h.power=d.power*(1+(p.power||0)*.12)*state.bonusPower;h.haste=Math.max(.43,1-(p.haste||0)*.08);h.area=1+(p.area||0)*.10;h.armor=Math.min(.58,(p.armor||0)*.06);h.magnet=d.magnet*(1+(p.magnet||0)*.18);h.crit=d.crit+(p.crit||0)*.06;h.regen=(p.regen||0)*.0035;h.projectiles=1+Math.floor((p.projectiles||0)*.6);h.duration=1+(p.duration||0)*.12;h.xpGain=1+(p.exp||0)*.10;if(oldMax>0&&h.hp>0)h.hp=Math.min(h.maxHp,h.hp/oldMax*h.maxHp);else h.hp=Math.min(h.hp,h.maxHp)}
async function startRun(){
 if(state.running||state.starting)return;state.starting=true;audioStart();$('#startBtn').disabled=true;$('#startBtn').textContent='载入战斗模型…';state.paused=true;await preloadModels();if(hangarActor)hangarActor.visible=false;resetSceneObjects();clearInput();$('#mainObjective').textContent='坚守 10 分钟 · 摧毁 OMEGA';Object.assign(state,{running:false,paused:true,time:0,kills:0,level:1,xp:0,xpNeed:12,coins:0,charge:0,diff:selectedDiff,char:'vanguard',wave:0,spawnAcc:0,lastElite:0,lastChest:0,lastEvent:0,eventCount:0,evolutions:0,elitesKilled:0,boss:null,bossStarted:false,bossKilled:false,victory:false,minibossStage:0,newAchievements:[],questKills:false,questEvents:false,questEvo:false,bonusPower:1,weapons:{},passives:{},pendingUnlock:null,ultSequence:null,victoryAt:null});
 const c=CHARS.vanguard,base=derivedHero(c),vis=actorVisual(c.model,0x72eeff,3.45,.82,true),mesh=vis.root;mesh.position.set(0,0,0);scene.add(mesh);state.hero={mesh,hp:base.maxHp,maxHp:base.maxHp,speed:base.speed,power:base.power,haste:1,area:1,armor:0,magnet:base.magnet,crit:.05,regen:0,projectiles:1,duration:1,xpGain:1,skillCd:0,ultCd:0,invuln:0,shield:0,anim:makeMixer(mesh,vis.animations),fromAsset:vis.fromAsset,moving:false,coreKills:0,coreTime:0,barrier:null};state.weapons.pulse={lv:1,timer:.08,evo:false};refreshDerived();syncCamera();
 state.starting=false;state.running=true;state.paused=false;state.manualAim=false;document.body.classList.add('playing');$('#pauseBtn').classList.remove('hidden');$('#menu').classList.add('hidden');$('#resultModal').classList.add('hidden');$('#hud').classList.remove('hidden');$('#startBtn').disabled=false;$('#startBtn').innerHTML='部署 AEGIS-7 <span>↗</span>';for(let i=0;i<16;i++)spawnEnemy(i%5===0?'gunner':i%3===0?'alien':'drone',false,false,rand(7.5,13.5));clock.getDelta();updateAimLabel();showToast('协议启动 · 保持移动，回收能量');updateHUD(true)
}
$('#startBtn').onclick=startRun;$('#againBtn').onclick=()=>{$('#resultModal').classList.add('hidden');startRun()};$('#menuBtn').onclick=()=>{$('#resultModal').classList.add('hidden');$('#hud').classList.add('hidden');$('#menu').classList.remove('hidden');if(hangarActor)hangarActor.visible=true;if(state.hero)state.hero.mesh.visible=false;camera.position.set(0,10,16);camera.lookAt(0,1,0);renderMenu()};
function togglePause(){if(!$('#evolutionModal').classList.contains('hidden'))return;if(!state.running||!$('#levelModal').classList.contains('hidden'))return;clearInput();state.paused=!state.paused;$('#pauseModal').classList.toggle('hidden',!state.paused)}$('#resumeBtn').onclick=togglePause;$('#quitBtn').onclick=()=>{state.paused=false;$('#pauseModal').classList.add('hidden');endRun(false,true)};

function nearestEnemy(pos=state.hero.mesh.position,max=999){let best=null,bd=max*max;for(const e of state.enemies){if(e.dead)continue;const d=e.mesh.position.distanceToSquared(pos);if(d<bd){bd=d;best=e}}return best}
function enemyInRadius(pos,r){const rr=r*r;return state.enemies.filter(e=>!e.dead&&e.mesh.position.distanceToSquared(pos)<=rr)}
function validPos(p,rad=.55){const rr=Math.hypot(p.x,p.z);if(rr>44-rad)return false;for(const o of obstacles)if(Math.hypot(p.x-o.p.x,p.z-o.p.z)<o.rad+rad)return false;return true}
function moveWithCollision(obj,delta,rad=.6){const np=obj.position.clone().add(delta);if(validPos(np,rad))obj.position.copy(np);else{const px=obj.position.clone();px.x+=delta.x;if(validPos(px,rad))obj.position.x=px.x;const pz=obj.position.clone();pz.z+=delta.z;if(validPos(pz,rad))obj.position.z=pz.z}}
function spawnEnemy(type='drone',elite=false,boss=false,forcedDist=null){if(state.enemies.length>=(IS_TOUCH?82:128)&&!boss)return null;const key=boss?'boss':type,base=ENEMY_TYPES[key]||ENEMY_TYPES.drone,ang=Math.random()*Math.PI*2,dist=forcedDist??(boss?18:rand(9,16)),pos=state.hero.mesh.position.clone().add(new THREE.Vector3(Math.cos(ang)*dist,0,Math.sin(ang)*dist));if(Math.hypot(pos.x,pos.z)>42)pos.normalize().multiplyScalar(41.5);for(let attempt=0;attempt<24&&!validPos(pos,base.rad);attempt++){const a=ang+(attempt+1)*.41;pos.copy(state.hero.mesh.position).add(new THREE.Vector3(Math.cos(a)*dist,0,Math.sin(a)*dist));const rr=Math.hypot(pos.x,pos.z);if(rr>42)pos.multiplyScalar(41.5/rr)}if(!validPos(pos,base.rad))return null;const diff=DIFFS[state.diff].mul,scale=1+state.time/560*.72,hp=base.hp*diff*scale*(boss?1:(elite?4.3:1)),vis=actorVisual(base.model,base.color,boss?base.size:elite?base.size*1.28:base.size,boss?2.8:elite?1.25:base.rad+.46,false),mesh=vis.root;mesh.position.copy(pos);scene.add(mesh);const e={mesh,type:key,hp,maxHp:hp,speed:base.speed*(1+state.time/850*.3)*(boss?.86:1),dmg:base.dmg*diff*(boss?1:(elite?1.3:1)),rad:base.rad*(boss?1:(elite?1.22:1)),xp:base.xp*(elite?4:1),ranged:base.ranged||boss,shoot:boss?3:rand(.4,1.25),touch:0,elite,boss,dead:false,flash:0,charge:boss?3.2:rand(2.6,5.2),baseScale:mesh.scale.clone(),anim:makeMixer(mesh,vis.animations),moving:true,fromAsset:vis.fromAsset,hitVisual:false};state.enemies.push(e);if(elite)showToast(boss?'OMEGA · 巨型机甲核心进入战区':'精英单位进入视野');if(boss){state.boss=e;$('#bossWrap').classList.remove('hidden');$('#bossName').textContent='OMEGA · 深空机甲核心';$('#bossHp').style.width='100%'}return e}
function enemyFlashMaterials(e,on){if(!e?.mesh)return;e.mesh.traverse(o=>{if(!o.isMesh||!o.material)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const mat of mats){if(on){if(mat.color&&!mat.userData.vsHitBaseColor)mat.userData.vsHitBaseColor=mat.color.clone();if(mat.emissive&&!mat.userData.vsHitBaseEmissive)mat.userData.vsHitBaseEmissive=mat.emissive.clone();if(mat.userData.vsHitBaseIntensity===undefined)mat.userData.vsHitBaseIntensity=mat.emissiveIntensity||0;if(mat.color)mat.color.set(0xffffff);if(mat.emissive)mat.emissive.set(0xffffff);if('emissiveIntensity' in mat)mat.emissiveIntensity=2.8}else{if(mat.color&&mat.userData.vsHitBaseColor)mat.color.copy(mat.userData.vsHitBaseColor);if(mat.emissive&&mat.userData.vsHitBaseEmissive)mat.emissive.copy(mat.userData.vsHitBaseEmissive);if(mat.userData.vsHitBaseIntensity!==undefined)mat.emissiveIntensity=mat.userData.vsHitBaseIntensity}}});e.hitVisual=on}
function killEnemy(e){if(e.dead)return;audioCue('kill');e.dead=true;const deathPos=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?2.4:1.0,0));fxBurst(deathPos,e.boss?0xff5879:0x8ff4ff,e.boss?42:22,e.boss?2.2:1.35);fxRing(e.mesh.position,e.boss?4.2:1.55,e.boss?0xff557c:0x7eeeff);removeObject(e.mesh);state.kills++;triggerCore();state.charge=clamp(state.charge+(e.elite?8:1.1),0,100);spawnGem(e.mesh.position,e.xp);if(e.elite){state.elitesKilled++;spawnPickup(e.mesh.position,Math.random()<.6?'chest':'heart')}else if(Math.random()<.018)spawnPickup(e.mesh.position,pick(['heart','coin','magnet']));if(e.boss){state.bossKilled=true;state.victory=true;$('#bossWrap').classList.add('hidden');showToast('核心崩解 · 协议完成');state.victoryAt=state.time+.9}checkAchievements()}
function fxImpactEnemy(e,crit=false){const p=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?2.5:1.05,0)),col=crit?0xffd86b:0xf4fbff;fxBurst(p,col,crit?28:20,crit?1.6:1.25);fxRing(e.mesh.position,e.boss?2.2:1.05,crit?0xffd86b:0xff7d66);const s=new THREE.Mesh(new THREE.SphereGeometry(e.boss?.72:.42,12,8),new THREE.MeshBasicMaterial({toneMapped:false,color:col,transparent:true,opacity:.6,depthWrite:false}));s.position.copy(p);scene.add(s);state.fx.push({mesh:s,life:.18,max:.18,update:f=>{const t=1-f.life/f.max;f.mesh.scale.setScalar(1+t*1.8);f.mesh.material.opacity=(1-t)*.65}})}
function damageEnemy(e,dmg,critRoll=true){if(!e||e.dead||dmg<=0)return;const crit=critRoll&&Math.random()<state.hero.crit,d=dmg*(crit?1.85:1)*(state.hero.coreTime>0?1.15:1);e.hp-=d;audioCue('hit');e.flash=.14;e.mesh.scale.copy(e.baseScale).multiplyScalar(crit?1.09:1.065);enemyFlashMaterials(e,true);if(e.anim)e.anim.hitUntil=state.time+.14;fxImpactEnemy(e,crit);const numPos=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?4.1:2.0,0));if(!e.boss){const away=e.mesh.position.clone().sub(state.hero.mesh.position).setY(0);if(away.lengthSq()>.01)moveWithCollision(e.mesh,away.normalize().multiplyScalar(crit?.22:.13),e.rad)}damageNumber(numPos,Math.round(d),crit);if(e.boss)$('#bossHp').style.width=clamp(e.hp/e.maxHp*100,0,100)+'%';if(e.hp<=0)killEnemy(e)}
function hitHero(dmg){const h=state.hero;if(!h||h.invuln>0||state.victory)return;if(h.shield>0){const used=Math.min(h.shield,dmg);h.shield-=used;dmg-=used;if(h.barrier)h.barrier.absorbed=Math.min(h.maxHp,h.barrier.absorbed+used);if(dmg<=0){h.invuln=.08;fxRing(h.mesh.position,1.5,0x74efff);return}}dmg*=1-h.armor;h.hp-=dmg;h.invuln=.38;if(h.anim)h.anim.hitUntil=state.time+.28;fxBurst(h.mesh.position.clone().add(new THREE.Vector3(0,1.2,0)),0xff6688,8);if(h.hp<=0){h.hp=0;endRun(false)}}
function enemyShot(e,target,spd=8,dmg=e.dmg*.7){const pos=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?2.2:1.15,0)),dir=target.clone().sub(pos).setY(0).normalize(),m=boltVisual(e.boss?0xff4d79:0xff9a52,e.boss?1.35:.95,e.boss?.18:.13);m.position.copy(pos);orientBolt(m,dir);scene.add(m);fxBurst(pos,0xff9a52,5,.65);if(e.anim)e.anim.attackUntil=state.time+.2;state.enemyProjectiles.push({mesh:m,vel:dir.multiplyScalar(spd),dmg,life:5,rad:e.boss?.34:.26,color:e.boss?0xff4d79:0xff9a52})}
function bossPattern(e){const stage=e.attackIndex||0;e.attackIndex=stage+1;const phase=e.hp/e.maxHp<.5?2:1;e.windup=1.5;e.shoot=phase===2?3.8:4.8;const p=e.mesh.position.clone(),target=state.hero.mesh.position.clone();if(stage%3===0){telegraphSlam(e);return}if(stage%3===1){const aim=Math.atan2(target.x-p.x,target.z-p.z);for(const off of [-.48,0,.48])bossWarning(e,{type:'line',p:p.clone(),angle:aim+off,length:21,width:1.4,delay:1.5,name:'三线裁决 · 走入线间空隙'});return}bossWarning(e,{type:'radial',p:p.clone(),angle:Math.atan2(target.x-p.x,target.z-p.z),r:4,delay:1.5,name:'围猎弹幕 · 绿色缺口安全'})}
function telegraphSlam(e){e.windup=1.5;bossWarning(e,{type:'circle',p:e.mesh.position.clone(),r:6,delay:1.5,name:'断层重锤 · 离开红圈'})}
function bossWarning(e,a){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({toneMapped:false,color:0xff405e,transparent:true,opacity:.27,side:THREE.DoubleSide,depthWrite:false,depthTest:false}),m=new THREE.Mesh(a.type==='line'?new THREE.PlaneGeometry(a.width,a.length):new THREE.CircleGeometry(a.r,64),mat);m.rotation.x=-Math.PI/2;m.renderOrder=20;if(a.type==='line'){m.position.z=a.length/2;g.rotation.y=a.angle}g.add(m);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:0xff8497,depthTest:false}));m.add(edge);if(a.type==='radial'){const safe=new THREE.Mesh(new THREE.RingGeometry(4,8,32,1,a.angle-.44,.88),new THREE.MeshBasicMaterial({color:0x89ffd1,toneMapped:false,transparent:true,opacity:.4,side:THREE.DoubleSide,depthWrite:false,depthTest:false}));safe.rotation.x=-Math.PI/2;safe.rotation.z=-Math.PI/2;safe.renderOrder=21;g.add(safe)}g.position.copy(a.p);g.position.y=.15;scene.add(g);e.warning=a;state.fx.push({mesh:g,life:a.delay,max:a.delay,bossHazard:true,update:f=>{a.remaining=f.life;mat.opacity=.22+.14*Math.sin(f.life*15)**2;if(e.dead)f.life=0},end:()=>{if(!state.running||e.dead||state.victory)return;const hp=state.hero.mesh.position;let hit=false;if(a.type==='circle')hit=distSqXZ(hp,a.p)<(a.r+.4)**2;if(a.type==='line'){const end=a.p.clone().add(new THREE.Vector3(Math.sin(a.angle)*a.length,0,Math.cos(a.angle)*a.length));hit=segmentDistanceSq(a.p,end,hp)<(a.width/2+.4)**2;fxLine(a.p.clone().setY(.5),end.clone().setY(.5),0xff637d,.3)}if(hit)hitHero(e.dmg*1.5);if(a.type==='radial'){const count=e.hp/e.maxHp<.5?26:22;for(let i=0;i<count;i++){const angle=i/count*Math.PI*2,delta=Math.atan2(Math.sin(angle-a.angle),Math.cos(angle-a.angle));if(Math.abs(delta)<.52)continue;const dir=new THREE.Vector3(Math.sin(angle),0,Math.cos(angle)),bolt=boltVisual(0xff567a,1.2,.14);bolt.position.copy(a.p).setY(1.1);orientBolt(bolt,dir);scene.add(bolt);state.enemyProjectiles.push({mesh:bolt,vel:dir.multiplyScalar(5.5),dmg:e.dmg*.7,life:7,rad:.24,color:0xff567a})}}fxRing(a.p,a.r||3,0xff738a);if(e.warning===a)e.warning=null}})}



function boltVisual(color=0x71ecff,len=1.35,rad=.105){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.65,depthWrite:false}),core=new THREE.Mesh(new THREE.CylinderGeometry(rad*.38,rad*.38,len,6),new THREE.MeshBasicMaterial({toneMapped:false,color:0xf4ffff})),shell=new THREE.Mesh(new THREE.CylinderGeometry(rad*.8,rad*.55,len*.82,6),mat),tip=new THREE.Mesh(new THREE.ConeGeometry(rad*.85,len*.25,6),mat.clone()),tail=new THREE.Mesh(new THREE.ConeGeometry(rad*1.5,len*1.25,6),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.2,depthWrite:false}));tip.position.y=len*.51;tail.position.y=-len*.7;tail.rotation.z=Math.PI;g.add(tail,shell,core,tip);return g}


function orientBolt(m,dir){if(dir.lengthSq()<.001)return;m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.clone().normalize())}
function fxBurst(pos,color=0x7eeeff,count=10,power=1){if(state.fx.length>(IS_TOUCH?90:180))return;count=Math.min(count,IS_TOUCH?14:26);const mat=new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.98,depthWrite:false}),g=new THREE.InstancedMesh(new THREE.BoxGeometry(.048*power,.048*power,.36*power),mat,count),particles=[],dummy=new THREE.Object3D();g.frustumCulled=false;for(let i=0;i<count;i++)particles.push({p:pos.clone(),v:new THREE.Vector3(rand(-3.6,3.6)*power,rand(.8,4.8)*power,rand(-3.6,3.6)*power),r:new THREE.Euler(rand(0,3),rand(0,3),rand(0,3))});const update=(f,dt)=>{particles.forEach((s,i)=>{s.p.addScaledVector(s.v,dt);s.v.y-=7*dt;dummy.position.copy(s.p);dummy.rotation.copy(s.r);dummy.updateMatrix();g.setMatrixAt(i,dummy.matrix)});g.instanceMatrix.needsUpdate=true;mat.opacity=Math.max(0,f.life/f.max)};const fx={mesh:g,life:.34,max:.34,update};update(fx,0);scene.add(g);state.fx.push(fx)}
function projectile(pos,dir,speed,dmg,opt={}){dir=dir.clone().normalize();const m=opt.blade?bladeVisual(opt.color||0x73ffe0):boltVisual(opt.color||0x70ecff,opt.evo?2.05:(opt.len||1.45),opt.size||.11);m.position.copy(pos);orientBolt(m,dir);scene.add(m);fxLine(pos.clone().addScaledVector(dir,-.2),pos.clone().addScaledVector(dir,.9),opt.color||0x70ecff,.09);state.projectiles.push({mesh:m,vel:dir.multiplyScalar(speed),dmg,life:opt.life||3,maxLife:opt.life||3,age:0,pierce:opt.pierce||0,rad:opt.rad||.28,explode:opt.explode||0,homing:opt.homing||0,color:opt.color||0x70ecff,hit:new Set(),evo:!!opt.evo,returnAt:opt.returnAt||0,returning:false,bounce:opt.bounce||0,onHit:opt.onHit||null})}
function fireFan(origin,baseDir,count,spread,cb){if(count<=1)return cb(baseDir,0);const right=new THREE.Vector3(baseDir.z,0,-baseDir.x);for(let i=0;i<count;i++){const u=i/(count-1)-.5,dir=baseDir.clone().addScaledVector(right,u*spread).normalize();cb(dir,i)}}
function chainLightning(origin,damage,jumps,color){let from=origin.clone(),used=new Set();for(let i=0;i<jumps;i++){let best=null,bd=999;for(const e of state.enemies){if(e.dead||used.has(e))continue;const d=distSqXZ(from,e.mesh.position);if(d<bd&&d<100){bd=d;best=e}}if(!best)break;used.add(best);const to=best.mesh.position.clone().add(new THREE.Vector3(0,1,0));lightningArc(from,to,color);fxBurst(to,color,7,.7);damageEnemy(best,damage*(1-i*.07));from=to}}
function orbitalStrike(pos,damage,r,color){const ring=new THREE.Mesh(new THREE.RingGeometry(r*.72,r,36),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(pos);ring.position.y=.08;scene.add(ring);state.fx.push({mesh:ring,life:.55,max:.55,update:f=>{const t=1-f.life/f.max;f.mesh.material.opacity=.35+.55*Math.sin(t*14)**2},end:()=>{const top=pos.clone().add(new THREE.Vector3(0,7,0));fxLine(top,pos.clone().add(new THREE.Vector3(0,.2,0)),color,.28);for(const e of enemyInRadius(pos,r))damageEnemy(e,damage);fxBurst(pos.clone().add(new THREE.Vector3(0,.5,0)),color,30,1.45);fxRing(pos,r,color)}})}
function fxSlicerBurst(r,count,color){const g=new THREE.Group();g.position.copy(state.hero.mesh.position);for(let i=0;i<count;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.14,.08,.95),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.9,depthWrite:false}));const a=i/count*Math.PI*2;b.position.set(Math.cos(a)*r,.75,Math.sin(a)*r);b.rotation.y=-a;g.add(b)}scene.add(g);state.fx.push({mesh:g,life:.42,max:.42,update:(f,dt)=>{f.mesh.position.copy(state.hero.mesh.position);f.mesh.rotation.y+=dt*10;for(const c of f.mesh.children)if(c.material)c.material.opacity=Math.max(0,f.life/f.max)},end:()=>{}})}
function weaponTick(dt){if(!state.hero)return;for(const [id,w] of Object.entries(state.weapons)){w.timer=(w.timer||0)-dt;if(w.timer>0)continue;fireWeapon(id,w)}}
function fireWeapon(id,w){const h=state.hero,p=h.mesh.position,lv=w.lv,evo=w.evo,pow=h.power,area=h.area,haste=h.haste,extra=h.projectiles-1,dur=h.duration;let t,dir,muzzle;
 if(id==='pulse'){t=nearestEnemy(p,22);if(t||state.manualAim){dir=state.manualAim?state.aim.clone():t.mesh.position.clone().sub(p).setY(0).normalize();muzzle=weaponMuzzle(h,dir);if(!state.manualAim)dir=t.mesh.position.clone().sub(muzzle).setY(0).normalize();const n=1+(lv>=3?1:0)+(evo?1:0)+Math.floor(extra*.5);fireFan(muzzle,dir,n,.26,(d)=>projectile(muzzle,d,evo?25:22,9.8*pow*(1+.22*(lv-1)),{color:evo?0xd994ff:0x6ff2ff,pierce:evo?4:Math.floor((lv-1)/3),homing:evo?.36:.08,evo}));audioCue('shot');fxBurst(muzzle,evo?0xd78cff:0x73efff,5,.75);if(h.anim)h.anim.attackUntil=state.time+.16}w.timer=(evo?.12:.30)*haste/(1+.075*(lv-1));return}
 if(id==='blade'){t=nearestEnemy(p,24);if(t){dir=state.manualAim?state.aim.clone():t.mesh.position.clone().sub(p).setY(0).normalize();muzzle=p.clone().add(new THREE.Vector3(0,1.0,0));const n=Math.min(5,1+Math.floor((lv-1)/2)+extra+(evo?1:0));fireFan(muzzle,dir,n,.52,(d)=>projectile(muzzle,d,17,16*pow*(1+.18*(lv-1)),{blade:true,color:0x73ffe0,pierce:evo?8:4,returnAt:evo?.42:.62,life:evo?2.0:1.65,rad:.34,evo}))}w.timer=(evo?1.05:1.55)*haste;return}
 if(id==='mine'){const n=Math.min(8,2+Math.floor(lv/2)+extra+(evo?2:0));for(let i=0;i<n;i++){const a=i/n*Math.PI*2+state.time*.7,rr=1.8+Math.random()*2.1,pos=p.clone().add(new THREE.Vector3(Math.cos(a)*rr,0.05,Math.sin(a)*rr));createMine(pos,22*pow*(1+.2*(lv-1)),2.1*area,evo)}w.timer=(evo?2.4:3.3)*haste;return}
 if(id==='chain'){chainLightning(p.clone().add(new THREE.Vector3(0,1.1,0)),14*pow*(1+.2*(lv-1)),3+lv+extra+(evo?3:0),evo?0xd790ff:0x72e9ff);w.timer=(evo?1.15:1.85)*haste;return}
 if(id==='orbital'){const targets=state.enemies.filter(e=>!e.dead).sort(()=>Math.random()-.5).slice(0,Math.min(7,1+Math.floor(lv/2)+extra+(evo?2:0)));for(const e of targets)orbitalStrike(e.mesh.position.clone(),28*pow*(1+.2*(lv-1)),(1.55+.16*lv)*area*(evo?1.2:1),evo?0xe398ff:0x78dfff);w.timer=(evo?3.2:4.6)*haste;return}
 if(id==='slicer'){const r=(2.5+.23*lv)*area*(evo?1.2:1),n=3+Math.floor(lv/2)+extra+(evo?2:0);fxSlicerBurst(r,n,evo?0xe9a0ff:0x9cf9ff);for(const e of enemyInRadius(p,r+.7))damageEnemy(e,10*pow*(1+.22*(lv-1)));w.timer=(evo?.58:.88)*haste;return}
 if(id==='ember'){t=nearestEnemy(p,26);if(t){dir=state.manualAim?state.aim.clone():t.mesh.position.clone().sub(p).setY(0).normalize();muzzle=p.clone().add(new THREE.Vector3(0,1.3,0));const r=(1.55+.18*lv)*area*(evo?1.25:1);projectile(muzzle,dir,18,13*pow*(1+.18*(lv-1)),{color:evo?0xff7af1:0xff9a5d,pierce:evo?2:0,onHit:(e,pos)=>createZone(pos.clone().setY(.05),r,8.5*pow*(1+.16*(lv-1)),(2.8+.35*lv)*dur*(evo?1.25:1),evo?0xff66dc:0xff7a48),evo})}w.timer=(evo?.72:1.12)*haste;return}
 if(id==='sentinel'){t=nearestEnemy(p,28);if(t){dir=t.mesh.position.clone().sub(p).setY(0).normalize();const right=new THREE.Vector3(dir.z,0,-dir.x),n=Math.min(5,1+Math.floor(lv/2)+extra+(evo?2:0));for(let i=0;i<n;i++){const side=(i-(n-1)/2)*.72,m=companions[i]?.position.clone()||p.clone().add(new THREE.Vector3(0,1.7,0)).addScaledVector(right,side);fxBurst(m,0x86a7ff,4,.6);projectile(m,dir.clone(),20,8.6*pow*(1+.17*(lv-1)),{color:evo?0xd28cff:0x86a7ff,homing:evo?.65:.35,pierce:evo?2:0,evo})}}w.timer=(evo?.38:.64)*haste;return}
 if(id==='echo'){t=nearestEnemy(p,28);if(t){dir=state.manualAim?state.aim.clone():t.mesh.position.clone().sub(p).setY(0).normalize();muzzle=p.clone().add(new THREE.Vector3(0,1.15,0));const n=Math.min(9,2+Math.floor(lv/2)+extra+(evo?3:0));fireFan(muzzle,dir,n,1.05,(d)=>projectile(muzzle,d,18,11.5*pow*(1+.17*(lv-1)),{blade:true,color:evo?0xf196ff:0x86f5d6,pierce:6,bounce:evo?5:2,life:3.4,rad:.3,evo}))}w.timer=(evo?1.15:1.7)*haste;return}
 if(id==='field'){const r=(2.45+.2*lv)*area*(evo?1.3:1);for(const e of enemyInRadius(p,r))damageEnemy(e,6.4*pow*(1+.2*(lv-1)));fxRing(p,r,evo?0xcc78ff:0x73e7ff);w.timer=(evo?.34:.52)*haste;return}
 if(id==='vortex'){const n=Math.min(12,4+lv+extra+(evo?2:0)),phase=(w.phase||0)+.58;w.phase=phase;for(let i=0;i<n;i++){const a=phase+i/n*Math.PI*2,dd=new THREE.Vector3(Math.cos(a),0,Math.sin(a));projectile(p.clone().add(new THREE.Vector3(0,1.0,0)),dd,13,7.5*pow*(1+.18*(lv-1)),{color:evo?0xf17cff:0x72dfff,pierce:evo?3:1,life:2.4,rad:.26,evo})}w.timer=(evo?.62:.92)*haste;return}
 if(id==='annihilator'){const r=(11+lv*.8)*area*(evo?1.2:1),dmg=38*pow*(1+.22*(lv-1));fxRing(p,r,evo?0xff9dea:0xf7e78a);fxBurst(p.clone().add(new THREE.Vector3(0,1.2,0)),evo?0xff9dea:0xf7e78a,40,2);for(const e of enemyInRadius(p,r))damageEnemy(e,dmg*((e.elite||e.boss)?.55:1));w.timer=(evo?7.4:11.2)*haste;return}}
function createMine(pos,dmg,r,evo){const m=new THREE.Mesh(new THREE.CylinderGeometry(.3,.4,.14,12),new THREE.MeshBasicMaterial({toneMapped:false,color:evo?0xd487ff:0x67dcff}));m.position.copy(pos);fxRing(pos,.8,evo?0xd487ff:0x67dcff);scene.add(m);state.fx.push({mesh:m,life:evo?2.1:2.7,max:evo?2.1:2.7,update:f=>{f.mesh.scale.setScalar(1+.18*Math.sin(state.time*8)),f.mesh.rotation.y+=.04},end:()=>{for(const e of enemyInRadius(pos,r*(evo?1.5:1)))damageEnemy(e,dmg*(evo?1.55:1));fxBurst(pos.clone().add(new THREE.Vector3(0,.3,0)),evo?0xe38bff:0x66dfff,22,1.4);fxRing(pos,r*(evo?1.5:1),evo?0xe38bff:0x66dfff)}})}
function createZone(pos,r,dps,dur,color,event=false){const m=new THREE.Mesh(new THREE.CircleGeometry(r,36),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:event?.18:.12,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.05;scene.add(m);state.zones.push({mesh:m,r,dps,life:dur,tick:0,event,capture:0,done:false})}
function fxRing(pos,r,color){const m=new THREE.Mesh(new THREE.RingGeometry(.88,1,40),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.75,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.12;scene.add(m);state.fx.push({mesh:m,life:.38,max:.38,update:f=>{const t=1-f.life/f.max;f.mesh.scale.setScalar(r*t);f.mesh.material.opacity=1-t}})}
function fxLine(a,b,color=0x68e9ff,width=.07){const d=b.clone().sub(a),len=d.length(),m=new THREE.Mesh(new THREE.CylinderGeometry(width,width,len,5),new THREE.MeshBasicMaterial({toneMapped:false,color,transparent:true,opacity:.8}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());scene.add(m);state.fx.push({mesh:m,life:.11,max:.11,update:f=>f.mesh.material.opacity=f.life/f.max})}
function damageNumber(world,n,crit){const layer=$('#damageLayer');if(layer.childElementCount>45)return;const p=world.clone().project(camera);if(p.z>1)return;const el=document.createElement('div');el.className='dmg';el.textContent=(crit?'✦ ':'')+n;el.style.color=crit?'#ffd578':'#d9f8ff';el.style.left=((p.x*.5+.5)*innerWidth)+'px';el.style.top=((-p.y*.5+.5)*innerHeight)+'px';layer.appendChild(el);setTimeout(()=>el.remove(),750)}

function spawnGem(pos,xp){const g=new THREE.Group(),core=new THREE.Mesh(new THREE.OctahedronGeometry(.18),new THREE.MeshBasicMaterial({toneMapped:false,color:0x8af0ff})),glow=new THREE.Mesh(new THREE.OctahedronGeometry(.31),new THREE.MeshBasicMaterial({toneMapped:false,color:0x5fd9ff,transparent:true,opacity:.18,depthWrite:false})),tail=new THREE.Mesh(new THREE.CylinderGeometry(.025,.065,1.15,6),new THREE.MeshBasicMaterial({toneMapped:false,color:0x63dcff,transparent:true,opacity:.48,depthWrite:false}));tail.visible=false;g.add(glow,core,tail);g.position.copy(pos);g.position.y=.28;scene.add(g);state.gems.push({mesh:g,core,glow,tail,xp,life:45,pull:false,pullAge:0,phase:Math.random()*Math.PI*2,vel:new THREE.Vector3()})}
function spawnPickup(pos,type){const col={heart:0x7bff9b,coin:0xffd06a,magnet:0x7f9cff,chest:0xd88cff}[type],m=new THREE.Mesh(new THREE.IcosahedronGeometry(type==='chest'?.34:.2,0),new THREE.MeshBasicMaterial({toneMapped:false,color:col}));m.position.copy(pos);m.position.y=.28;scene.add(m);state.pickups.push({mesh:m,type,life:36})}
function applyPickup(p){const h=state.hero;if(p.type==='heart')h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.3);if(p.type==='coin')state.coins+=22;if(p.type==='magnet')for(const g of state.gems)g.pull=true;if(p.type==='chest'){state.coins+=50;h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.2);showToast('补给箱：+50 CR · 修复装甲')}}
function flashHealScreen(){const f=$('#healFlash');f.classList.remove('show');void f.offsetWidth;f.classList.add('show');setTimeout(()=>f.classList.remove('show'),900)}
function addXp(v){state.xp+=v*(state.hero?.xpGain||1);if(state.paused||!state.running)return;while(state.xp>=state.xpNeed&&state.running){state.xp-=state.xpNeed;state.level++;state.xpNeed=Math.floor(state.xpNeed*1.18+5);if(state.hero){state.hero.hp=state.hero.maxHp;state.hero.shield=Math.max(state.hero.shield,state.hero.maxHp*.08)}if(state.level===3)state.pendingUnlock='E 棱镜壁垒已解锁';if(state.level===6)state.pendingUnlock='R 离子超载已解锁';audioCue('level');flashHealScreen();showToast('等级提升 · 装甲完全修复');openLevelUp();break}checkAchievements()}
function buildChoices(){const pool=[],unique=(o)=>{if(!pool.some(x=>x.kind===o.kind&&x.id===o.id))pool.push(o)},weaponCount=Object.keys(state.weapons).length,passiveCount=Object.keys(state.passives).length;
 for(const [id,w] of Object.entries(state.weapons)){const def=WEAPONS[id];if(w.lv>=def.max&&!w.evo&&(state.passives[def.pair]||0)>=3)unique({kind:'evo',id,name:def.evo,desc:`完成 ${def.name} 的形态进化，攻击机制显著强化。`,pair:def.pair});else if(w.lv<def.max)unique({kind:'weapon',id,name:def.name,desc:def.desc,pair:def.pair})}
 if(weaponCount<5)for(const [id,def] of Object.entries(WEAPONS))if(!state.weapons[id])unique({kind:'weapon',id,name:def.name,desc:def.desc,pair:def.pair,newCard:true});
 for(const [id,p] of Object.entries(PASSIVES)){const lv=state.passives[id]||0;if(lv>0&&lv<p.max)unique({kind:'passive',id,name:p.name,desc:p.desc});else if(lv===0&&passiveCount<6)unique({kind:'passive',id,name:p.name,desc:p.desc,newCard:true})}
 const c=[];while(c.length<3&&pool.length){let ticket=Math.random()*pool.reduce((n,x)=>n+choiceWeight(x),0),at=pool.length-1;for(let i=0;i<pool.length;i++){ticket-=choiceWeight(pool[i]);if(ticket<0){at=i;break}}c.push(pool.splice(at,1)[0])}const utils=[{kind:'utility',id:'repair',name:'紧急纳米修复',desc:'立即获得 30% 护盾，并回满生命。'},{kind:'utility',id:'credits',name:'战场回收',desc:'立即获得 75 CR。'},{kind:'utility',id:'overclock',name:'临时过载',desc:'本局永久伤害 +6%。'}];while(c.length<3){const u=utils[c.length%utils.length];if(!c.some(x=>x.id===u.id))c.push(u);else c.push(utils[(c.length+1)%utils.length])}return c.slice(0,3)}
function cardNextText(c,lv){if(c.kind==='utility')return '即时战术收益';const ids=c.kind==='passive'?Object.keys(WEAPONS).filter(id=>WEAPONS[id].pair===c.id):[c.id];const head=c.kind==='weapon'?(c.newCard?'新增战斗机制':weaponUpgradeText(c.id,lv)):c.kind==='passive'?(c.newCard?'占用 1 个属性槽':'强化已安装属性'):'进化后改变攻击形态';return head+(choiceWeight(c)>1?'<span class="synergy">契合构筑 · 抽取权重小幅提升</span>':'')+(ids.length?ids.map(id=>evolutionRow(id,true)).join(''):'<span class="evoNote">通用强化 · 无专属进化配方</span>')}
function choiceWeight(c){if(c.kind==='evo')return 1.4;if(c.kind==='weapon')return state.passives[WEAPONS[c.id].pair]?1.25:1;if(c.kind==='passive')return Object.entries(state.weapons).some(([id,w])=>!w.evo&&WEAPONS[id].pair===c.id)?1.25:1;return 1}
function evolutionRow(id,compact=false){const d=WEAPONS[id],w=state.weapons[id],pl=state.passives[d.pair]||0,ready=w?.lv>=5&&pl>=3,blocked=(!w&&Object.keys(state.weapons).length>=5)||(!pl&&Object.keys(state.passives).length>=6);return `<div class="evoRecipe ${w?.evo?'complete':ready?'ready':''}">${compact?'':icon(id)}<div><b>${d.evo}</b><span>${d.name} ${w?.lv||0}/5 + ${PASSIVES[d.pair].name} ${pl}/3</span><div class="evoSteps">${Array.from({length:5},(_,i)=>`<i class="${i<(w?.lv||0)?'lit':''}"></i>`).join('')}<em>+</em>${Array.from({length:3},(_,i)=>`<i class="attr ${i<pl?'lit':''}"></i>`).join('')}</div><small>${w?.evo?'已完成进化':blocked?'槽位已满 · 本局无法补齐':ready?'条件齐全 · 升级时有机会出现进化卡':`还需：${!w||w.lv<5?'技能 Lv.5 ':''}${pl<3?PASSIVES[d.pair].name+' Lv.3':''}`}</small></div></div>`}
function openGuide(){state.guideFocus=document.activeElement;clearInput();state.guideWasPaused=state.paused;state.paused=true;$('#evolutionList').innerHTML=Object.keys(WEAPONS).map(id=>evolutionRow(id)).join('');$('#evolutionModal').classList.remove('hidden');$('#guideClose').focus()}
function closeGuide(){$('#evolutionModal').classList.add('hidden');state.paused=state.guideWasPaused;state.guideFocus?.focus();}


function openLevelUp(){state.paused=true;const box=$('#choices');box.innerHTML='';for(const c of buildChoices()){const b=document.createElement('button');b.className='choice '+c.kind;let lv=c.kind==='weapon'?state.weapons[c.id]?.lv||0:c.kind==='passive'?state.passives[c.id]||0:0,type=c.kind==='weapon'?'技能卡':c.kind==='passive'?'属性卡':c.kind==='evo'?'进化卡':'战术卡';b.innerHTML=`<span class="cardIndex">0${box.children.length+1}</span><div class="cardType">${type}${c.newCard?' · NEW':''}</div><div class="ico">${icon(c.id)}</div><div class="level">${c.kind==='evo'?'EVOLUTION':c.kind==='utility'?'UTILITY':`LV ${lv} → ${lv+1}`}</div><h3>${c.name}</h3><p>${c.desc}</p><div class="next">${cardNextText(c,lv)}</div>`;b.onclick=()=>selectChoice(c);box.appendChild(b)}$('#buildSummary').innerHTML=buildInventory();$('#levelModal').classList.remove('hidden')}
function selectChoice(c){if(!state.running||!state.paused||!$('#evolutionModal').classList.contains('hidden')||$('#levelModal').classList.contains('hidden'))return;audioCue('select');clearInput();if(c.kind==='weapon'){if(!state.weapons[c.id])state.weapons[c.id]={lv:1,timer:.08,evo:false};else state.weapons[c.id].lv++}else if(c.kind==='passive'){state.passives[c.id]=(state.passives[c.id]||0)+1;refreshDerived()}else if(c.kind==='evo'){state.weapons[c.id].evo=true;state.evolutions++;state.questEvo=true;showToast('技能进化 · '+WEAPONS[c.id].evo)}else if(c.id==='repair'){state.hero.shield+=state.hero.maxHp*.3}else if(c.id==='credits')state.coins+=75;else if(c.id==='overclock'){state.bonusPower*=1.06;refreshDerived()}refreshDerived();state.hero.hp=state.hero.maxHp;fxRing(state.hero.mesh.position,2.8,0x78ffad);fxBurst(state.hero.mesh.position.clone().add(new THREE.Vector3(0,1,0)),0x79ffae,16,1);$('#levelModal').classList.add('hidden');state.paused=false;if(state.pendingUnlock){showToast(state.pendingUnlock);state.pendingUnlock=null}updateHUD(true);checkAchievements();if(state.xp>=state.xpNeed)addXp(0)}

function useSkill(){if(!state.running||state.paused||!state.hero)return;const h=state.hero;if(state.level<3){showToast('棱镜壁垒 · LV3 解锁');return}if(h.skillCd>0)return;h.skillCd=12*h.haste;h.shield=Math.min(h.maxHp,h.shield+h.maxHp*.35);h.barrier={left:3,pulse:0,absorbed:0};const g=new THREE.Group();for(let i=0;i<6;i++){const a=i*Math.PI/3,m=new THREE.Mesh(new THREE.PlaneGeometry(1.25,1.8),new THREE.MeshBasicMaterial({color:0x6cf6e1,toneMapped:false,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}));m.position.set(Math.sin(a)*2.2,1.3,Math.cos(a)*2.2);m.rotation.y=a;g.add(m);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:0x8effeb,transparent:true,opacity:.8}));m.add(outline)}g.position.copy(h.mesh.position);scene.add(g);state.fx.push({mesh:g,life:3,max:3,update:(f,dt)=>{f.mesh.position.copy(h.mesh.position);f.mesh.rotation.y+=dt*.65}});fxRing(h.mesh.position,2.8,0x83ffe6);audioCue('dash');showToast('E · 棱镜壁垒 / 3 秒后反击');updateCooldowns()}
function triggerCore(){const h=state.hero;if(!h)return;h.coreKills=(h.coreKills||0)+1;if(h.coreKills>=12){h.coreKills=0;h.coreTime=4;h.shield=Math.min(h.maxHp,h.shield+h.maxHp*.10);fxRing(h.mesh.position,2.1,0xffd178);fxBurst(h.mesh.position.clone().add(new THREE.Vector3(0,1.5,0)),0xffd178,12,.8);showToast('被动 · 自适应核心 / 火力 +15% · 护盾 +10%')}}
function updateDefense(dt){const h=state.hero;h.coreTime=Math.max(0,(h.coreTime||0)-dt);const b=h.barrier;if(!b)return;b.left-=dt;b.pulse-=dt;if(b.pulse<=0){b.pulse=1;fxRing(h.mesh.position,3.4,0x7bffde);for(const e of enemyInRadius(h.mesh.position,3.4))damageEnemy(e,14*h.power)}if(b.left<=0){h.barrier=null;const r=5.5*h.area;for(const e of enemyInRadius(h.mesh.position,r))damageEnemy(e,(55+b.absorbed*.65)*h.power);fxRing(h.mesh.position,r,0xb4fff0);fxSlicerBurst(r,12,0x8dffe8);fxBurst(h.mesh.position.clone().setY(1.2),0xc1ffee,24,1.5);showToast('棱镜反击 · '+Math.round(55+b.absorbed*.65)+' 基础伤害')}}


function createUltArray(){const h=state.hero,g=new THREE.Group();g.position.copy(h.mesh.position);for(const rr of [1.8,3.2,4.5]){const ring=new THREE.Mesh(new THREE.RingGeometry(rr*.94,rr,48),new THREE.MeshBasicMaterial({toneMapped:false,color:0xd88cff,transparent:true,opacity:.55,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;g.add(ring)}for(let i=0;i<8;i++){const a=i/8*Math.PI*2,b=new THREE.Mesh(new THREE.BoxGeometry(.08,.06,1.5),new THREE.MeshBasicMaterial({toneMapped:false,color:0xf0a8ff,transparent:true,opacity:.62,depthWrite:false}));b.position.set(Math.cos(a)*4,.16,Math.sin(a)*4);b.rotation.y=-a;g.add(b)}for(let i=0;i<6;i++){const a=i/6*Math.PI*2,lance=boltVisual(0xcc9bff,1.8,.08);lance.position.set(Math.cos(a)*3.2,3.2,Math.sin(a)*3.2);g.add(lance)}scene.add(g);state.fx.push({mesh:g,life:3.6,max:3.6,update:(f,dt)=>{f.mesh.position.copy(h.mesh.position);f.mesh.rotation.y+=dt*1.8;const k=.75+.25*Math.sin(state.time*8);f.mesh.scale.setScalar(k)}})}
function useUlt(){if(!state.running||state.paused||!state.hero)return;if(state.level<6){showToast('离子超载 · LV6 解锁');return}if(state.charge<100){showToast(`离子超载充能 ${Math.floor(state.charge)}% / 100%`);return}if(state.ultSequence)return;const h=state.hero;state.charge=0;h.shield+=h.maxHp*.45;h.invuln=.7;state.ultSequence={left:42,timer:0,duration:3.5,elapsed:0,strike:0};audioCue('ult');createUltArray();fxBurst(h.mesh.position.clone().add(new THREE.Vector3(0,1.4,0)),0xd98cff,30,1.6);showToast('R · 离子超载 / 天罚阵列');updateCooldowns()}
function updateSkillSequence(dt){const u=state.ultSequence;if(!u)return;u.elapsed+=dt;u.timer-=dt;u.strike-=dt;if(u.strike<=0){u.strike=.65;const target=nearestEnemy(state.hero.mesh.position,30);if(target)orbitalStrike(target.mesh.position.clone(),38*state.hero.power,2.6*state.hero.area,0xe4a6ff)}if(u.left>0&&u.timer<=0){u.timer=.07;u.left--;const h=state.hero,t=nearestEnemy(h.mesh.position,38);if(t){const d=t.mesh.position.clone().sub(h.mesh.position).setY(0).normalize(),m=h.mesh.position.clone().add(new THREE.Vector3(0,1.6,0)).addScaledVector(d,.85);projectile(m,d,28,19*h.power,{color:0xe49bff,pierce:4,homing:.42,evo:true,life:2.2})}}if(u.elapsed>=u.duration){const h=state.hero,r=9*h.area;for(const e of enemyInRadius(h.mesh.position,r))damageEnemy(e,90*h.power);fxRing(h.mesh.position,r,0xf1a2ff);fxSlicerBurst(r,16,0xf1c6ff);fxLine(h.mesh.position.clone().setY(12),h.mesh.position.clone().setY(.2),0xf3dfff,.5);fxBurst(h.mesh.position.clone().add(new THREE.Vector3(0,1.2,0)),0xf0a2ff,42,1.8);state.ultSequence=null;showToast('离子超载 · 终端冲击')}}
function updateSkillHUD(){const h=state.hero;if(!h)return;$('#coreStatus').innerHTML=icon('core')+`<span>自适应核心 <b>${h.coreTime>0?'超频 '+h.coreTime.toFixed(1)+'s':(h.coreKills||0)+'/12 击杀'}</b></span>`;const eLocked=state.level<3,rLocked=state.level<6,ec=$('#skillECard'),rc=$('#skillRCard');ec.classList.toggle('locked',eLocked);rc.classList.toggle('locked',rLocked);$('#skillEState').textContent=eLocked?'LV3 解锁':h.barrier?`防御 ${h.barrier.left.toFixed(1)}s`:h.skillCd>0?`${h.skillCd.toFixed(1)}s`:'READY';$('#skillRState').textContent=rLocked?'LV6 解锁':state.ultSequence?'释放中':state.charge>=100?'READY':`充能 ${Math.floor(state.charge)}%`;$('#eBtnText').textContent=eLocked?'E · Lv3':h.skillCd>0?'E '+h.skillCd.toFixed(1)+'s':'E 就绪';$('#rBtnText').textContent=rLocked?'R · Lv6':state.ultSequence?'R 释放中':'R '+Math.floor(state.charge)+'%';$('#eBtn').disabled=eLocked;$('#rBtn').disabled=rLocked}
function updateCooldowns(){const h=state.hero;if(!h)return;const eMask=$('#eBtn .coolMask'),rMask=$('#rBtn .coolMask');eMask.style.transform=`scaleY(${clamp(h.skillCd/(12*h.haste),0,1)})`;rMask.style.transform=`scaleY(${state.level>=6&&state.charge<100?1-state.charge/100:0})`;updateSkillHUD()}
function updateAimLabel(){$('#aimLabel').textContent='瞄准：'+(state.manualAim?'手动':'自动')+'（T切换）';$('#autoBtn').textContent=state.manualAim?'MANUAL AIM':'AUTO AIM'}

function updateHero(dt){const h=state.hero;if(!h)return;let x=(key.KeyD||key.ArrowRight?1:0)-(key.KeyA||key.ArrowLeft?1:0)+moveTouch.x,z=(key.KeyS||key.ArrowDown?1:0)-(key.KeyW||key.ArrowUp?1:0)+moveTouch.y,dir=new THREE.Vector3(x,0,z);if(dir.lengthSq()>1)dir.normalize();h.moving=dir.lengthSq()>.015;moveWithCollision(h.mesh,dir.multiplyScalar(h.speed*dt),.6);if(h.regen>0)h.hp=Math.min(h.maxHp,h.hp+h.maxHp*h.regen*dt);h.invuln=Math.max(0,h.invuln-dt);h.skillCd=Math.max(0,h.skillCd-dt);h.ultCd=Math.max(0,h.ultCd-dt);if(state.manualAim){if(IS_TOUCH){if(aimTouch.lengthSq()>.04)state.aim.set(aimTouch.x,0,aimTouch.y).normalize()}else{const ndc=new THREE.Vector2(mouse.x/innerWidth*2-1,-mouse.y/innerHeight*2+1),ray=new THREE.Raycaster();ray.setFromCamera(ndc,camera);const hit=new THREE.Vector3();const hasHit=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit);if(hasHit)state.aim.copy(hit.sub(h.mesh.position).setY(0).normalize())}}else{const t=nearestEnemy(h.mesh.position,60);if(t)state.aim.copy(t.mesh.position.clone().sub(h.mesh.position).setY(0).normalize())}if(state.aim.lengthSq()<.1)state.aim.set(0,0,-1);h.mesh.rotation.y=Math.atan2(state.aim.x,state.aim.z);syncCamera();updateAnim(h.anim,dt,h.moving);updateCooldowns()}
function updateEnemies(dt){const hp=state.hero.mesh.position;for(const e of state.enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);if(e.flash<=0){e.mesh.scale.lerp(e.baseScale,.24);if(e.hitVisual)enemyFlashMaterials(e,false);}e.touch-=dt;e.shoot-=dt;e.charge-=dt;e.windup=Math.max(0,(e.windup||0)-dt);if(e.slow>0)e.slow-=dt;for(const other of state.enemies){if(other===e||other.dead||e.boss)continue;const dx=e.mesh.position.x-other.mesh.position.x,dz=e.mesh.position.z-other.mesh.position.z,dd=dx*dx+dz*dz,min=(e.rad+other.rad)*.8;if(dd>0.0001&&dd<min*min){const k=(min-Math.sqrt(dd))*dt*2/Math.sqrt(dd);e.mesh.position.x+=dx*k;e.mesh.position.z+=dz*k}}const d=Math.sqrt(distSqXZ(hp,e.mesh.position)),dir=hp.clone().sub(e.mesh.position).setY(0).normalize(),speed=e.speed*(e.slow>0?.38:1);steerAroundProps(e.mesh.position,dir,e.rad,e.mesh.id);if(e.ranged&&!e.boss&&d<13){if(d<7)moveWithCollision(e.mesh,dir.clone().multiplyScalar(-speed*.42*dt),e.rad);else if(d>10)moveWithCollision(e.mesh,dir.clone().multiplyScalar(speed*.55*dt),e.rad);if(e.shoot<=0){enemyShot(e,hp.clone().add(new THREE.Vector3(0,1,0)));e.shoot=rand(1.55,2.4)}}else if(!e.boss||!e.windup)moveWithCollision(e.mesh,dir.multiplyScalar(speed*dt),e.rad);if(e.boss&&e.shoot<=0)bossPattern(e);if(d<e.rad+.62&&e.touch<=0){hitHero(e.dmg);e.touch=.72}e.mesh.rotation.y=Math.atan2(dir.x,dir.z);if(e.type==='drone')e.mesh.position.y=.55+Math.sin(state.time*5+e.mesh.id)*.08;else e.mesh.position.y=0;updateAnim(e.anim,dt,true)}state.enemies=state.enemies.filter(e=>!e.dead)}
function updateProjectiles(dt){for(const p of state.projectiles){p.life-=dt;p.age+=dt;const prev=p.mesh.position.clone();if(p.returnAt&&!p.returning&&p.age>=p.returnAt){p.returning=true;p.hit.clear()}if(p.returning){const d=state.hero.mesh.position.clone().sub(p.mesh.position).setY(0);if(d.lengthSq()>.01)p.vel.lerp(d.normalize().multiplyScalar(Math.max(13,p.vel.length())),clamp(4.5*dt,0,1))}else if(p.homing>0){const t=nearestEnemy(p.mesh.position,12);if(t){const d=t.mesh.position.clone().sub(p.mesh.position).setY(0).normalize().multiplyScalar(p.vel.length());p.vel.lerp(d,clamp(p.homing*dt,0,1))}}orientBolt(p.mesh,p.vel);p.mesh.position.addScaledVector(p.vel,dt);if(p.bounce>0&&Math.hypot(p.mesh.position.x,p.mesh.position.z)>43){const n=new THREE.Vector3(p.mesh.position.x,0,p.mesh.position.z).normalize(),dot=p.vel.dot(n);p.vel.addScaledVector(n,-2*dot);const rr=Math.hypot(p.mesh.position.x,p.mesh.position.z);if(rr>42.7){p.mesh.position.x*=42.7/rr;p.mesh.position.z*=42.7/rr}p.bounce--;p.hit.clear();fxBurst(p.mesh.position.clone(),p.color,5,.55)}for(const e of state.enemies){if(e.dead||p.hit.has(e))continue;if(segmentDistanceSq(prev,p.mesh.position,e.mesh.position)<(p.rad+e.rad+.22)**2){p.hit.add(e);fxBurst(p.mesh.position.clone(),p.color,p.evo?15:9,p.evo?1.05:.8);damageEnemy(e,p.dmg);p.onHit?.(e,p.mesh.position.clone());if(p.explode>0){for(const x of enemyInRadius(e.mesh.position,p.explode))if(x!==e)damageEnemy(x,p.dmg*.65);fxRing(e.mesh.position,p.explode,p.color)}if(p.pierce>0)p.pierce--;else{p.life=0;break}}}if(p.returning&&distSqXZ(p.mesh.position,state.hero.mesh.position)<.5)p.life=0}
 for(const p of state.projectiles)if(p.life<=0)removeObject(p.mesh);state.projectiles=state.projectiles.filter(p=>p.life>0);for(const p of state.enemyProjectiles){const prev=p.mesh.position.clone();p.life-=dt;orientBolt(p.mesh,p.vel);p.mesh.position.addScaledVector(p.vel,dt);if(state.hero.barrier&&segmentDistanceSq(prev,p.mesh.position,state.hero.mesh.position)<(2.5+p.rad)**2){state.hero.barrier.absorbed=Math.min(state.hero.maxHp,state.hero.barrier.absorbed+p.dmg);fxRing(p.mesh.position,.6,0x8dffe8);p.life=0;continue}if(segmentDistanceSq(prev,p.mesh.position,state.hero.mesh.position)<(.68+p.rad)**2){fxBurst(p.mesh.position.clone(),p.color||0xff704f,10,1);hitHero(p.dmg);p.life=0}}for(const p of state.enemyProjectiles)if(p.life<=0)removeObject(p.mesh);state.enemyProjectiles=state.enemyProjectiles.filter(p=>p.life>0)}
function updateZones(dt){for(const z of state.zones){z.life-=dt;z.tick-=dt;z.mesh.material.opacity=(z.event?.14:.09)+(z.event?.08:.04)*Math.sin(state.time*5);if(!z.event&&z.tick<=0){for(const e of enemyInRadius(z.mesh.position,z.r))damageEnemy(e,z.dps*.35,false);z.tick=.35}}for(const z of state.zones)if(z.life<=0)removeObject(z.mesh);state.zones=state.zones.filter(z=>z.life>0)}
function updateFX(dt){for(const f of state.fx){f.life-=dt;f.update?.(f,dt);if(f.life<=0){f.end?.();removeObject(f.mesh)}}state.fx=state.fx.filter(f=>f.life>0)}
function updateDrops(dt){const hp=state.hero.mesh.position,targetBase=hp.clone().add(new THREE.Vector3(0,.78,0));for(const g of state.gems){g.life-=dt;g.core.rotation.y+=dt*5;g.glow.rotation.y-=dt*2.5;let d=Math.sqrt(distSqXZ(g.mesh.position,hp));if(d<state.hero.magnet||g.pull){if(!g.pull){g.pull=true;fxRing(g.mesh.position,.5,0x8ce6e0)}g.pullAge+=dt;const target=targetBase.clone(),to=target.sub(g.mesh.position),dist=Math.max(.001,to.length()),dir=to.clone().normalize(),tangent=new THREE.Vector3(-dir.z,0,dir.x).multiplyScalar(Math.sin(g.pullAge*11+g.phase)*Math.min(2.0,dist*.24));const desired=dir.multiplyScalar(7+Math.min(27,g.pullAge*20)+12/(dist+.7)).add(tangent);g.vel.lerp(desired,clamp(dt*6.5,0,1));g.mesh.position.addScaledVector(g.vel,Math.min(dt,dist/Math.max(.01,g.vel.length())));const vdir=g.vel.clone().normalize();g.tail.visible=true;g.tail.scale.y=clamp(g.vel.length()/10,.55,2.3);g.tail.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),vdir.clone().multiplyScalar(-1));g.tail.position.copy(vdir).multiplyScalar(-.48);const sc=clamp(dist/2.5,.28,1);g.core.scale.setScalar(sc);g.glow.scale.setScalar(sc*(1.2+.2*Math.sin(state.time*14+g.phase)))}if(g.pull&&g.mesh.position.distanceTo(targetBase)<.55){audioCue('xp');addXp(g.xp);fxBurst(targetBase.clone(),0x82ecff,6,.55);g.life=0}}
 for(const g of state.gems)if(g.life<=0)removeObject(g.mesh);state.gems=state.gems.filter(g=>g.life>0);for(const p of state.pickups){p.life-=dt;p.mesh.rotation.y+=dt*2;if(p.mesh.position.distanceTo(hp)<.75){applyPickup(p);p.life=0}}for(const p of state.pickups)if(p.life<=0)removeObject(p.mesh);state.pickups=state.pickups.filter(p=>p.life>0)}
function updateEventZones(dt){for(const z of state.zones){if(!z.event||z.done)continue;const inside=state.hero.mesh.position.distanceTo(z.mesh.position)<z.r;z.capture=clamp(z.capture+(inside?dt:-dt*.35),0,8);if(z.capture>=8){z.done=true;z.life=.12;state.eventCount++;state.coins+=65;state.hero.hp=Math.min(state.hero.maxHp,state.hero.hp+state.hero.maxHp*.25);showToast('反应堆稳定 · +65 CR');if(state.eventCount>=2)state.questEvents=true}}}
function spawnDirector(dt){if(state.bossStarted)return;if(state.time>=600){const boss=spawnEnemy('boss',true,true);if(boss){state.bossStarted=true;$('#mainObjective').textContent='击败 OMEGA · 躲开红色预警';for(const e of state.enemies)if(!e.boss){e.dead=true;removeObject(e.mesh)}state.enemies=state.enemies.filter(e=>!e.dead);for(const p of state.enemyProjectiles)removeObject(p.mesh);state.enemyProjectiles=[];showToast('第 20 波结束 · OMEGA 决战')}}if(state.bossStarted)return;const wave=Math.min(20,Math.floor(state.time/30)+1);if(wave!==state.wave){state.wave=wave;showToast(`第 ${wave} / 20 波 · ${wave<4?'侦察群':wave<10?'混合攻势':wave<16?'重装围攻':'终末封锁'}`)}state.spawnAcc+=dt;const t=state.time,d=DIFFS[state.diff].mul,interval=Math.max(.14,.52-t/650*.34)/d;if(state.spawnAcc>interval){state.spawnAcc=0;const pool=t<90?['drone','drone','alien']:t<260?['drone','alien','gunner','brute']:['drone','alien','gunner','brute','gunner'];const n=1+(t>220?1:0)+(t>420&&Math.random()<.35?1:0);for(let i=0;i<n;i++)spawnEnemy(pick(pool),false,false,rand(9,16))}if(t-state.lastElite>58&&!state.bossStarted){state.lastElite=t;spawnEnemy(pick(['brute','gunner']),true)}const miniTimes=[150,330,480];if(state.minibossStage<miniTimes.length&&t>=miniTimes[state.minibossStage]){spawnEnemy('brute',true);state.minibossStage++;showToast(`精英阶段 ${state.minibossStage}/3 · 重装单位进入`)}if(t-state.lastChest>76){state.lastChest=t;const a=Math.random()*Math.PI*2;spawnPickup(new THREE.Vector3(Math.cos(a)*rand(8,20),0,Math.sin(a)*rand(8,20)),'chest');showToast('补给信标已投放')}if(t-state.lastEvent>88&&state.eventCount<4){state.lastEvent=t;const d=world.eventPoints[state.eventCount%world.eventPoints.length],p=new THREE.Vector3(d.x,0,d.z);createZone(p,2.5,0,55,d.color,true);state.zones[state.zones.length-1].label=d.name;showToast('地图事件 · 前往'+d.name+'稳定能源')}}
function checkAchievements(){const newly=[];for(const [id,a] of Object.entries(ACH))if(!meta.ach[id]&&a.test(state)){meta.ach[id]=Date.now();state.newAchievements.push(a.name);newly.push(a.name)}if(newly.length){saveMeta();showToast('成就解锁 · '+newly[0])}}
function updateQuests(){if(state.kills>=180)state.questKills=true;if(state.evolutions>=1)state.questEvo=true;$('#quest1').textContent=(state.questKills?'✓':'□')+' 击杀 180 个异兽';$('#quest2').textContent=(state.questEvents?'✓':'□')+' 完成 2 次地图事件';$('#quest3').textContent=(state.questEvo?'✓':'□')+' 完成 1 次武器进化';const event=state.zones.find(z=>z.event&&!z.done),nav=$('#eventNav');nav.classList.toggle('hidden',!event);if(event){const dx=event.mesh.position.x-state.hero.mesh.position.x,dz=event.mesh.position.z-state.hero.mesh.position.z,angle=Math.atan2(dx,-dz),arrows=['↑','↗','→','↘','↓','↙','←','↖'],arrow=arrows[(Math.round(angle/(Math.PI/4))+8)%8];nav.textContent=arrow+' '+(event.label||'能源事件')+' · '+Math.round(Math.hypot(dx,dz))+'m · 稳定 '+Math.round(event.capture/8*100)+'%'}}
function updateHUD(force=false){if(!state.hero)return;document.body.classList.toggle('bossFight',state.bossStarted&&!state.bossKilled);$('#waveLabel').textContent=state.bossStarted?'OMEGA / 最终决战':`WAVE ${String(state.wave||1).padStart(2,'0')} / 20`;if(state.boss){const e=state.boss;$('#bossAttack').textContent=e.warning?`${e.warning.name} · ${Math.max(0,e.warning.remaining||0).toFixed(1)}s`:`${e.hp/e.maxHp<.5?'Ⅱ / 核心狂暴':'Ⅰ / 装甲形态'} · 保持移动`;}const loc=state.hero.mesh.position,nearest=DISTRICTS.reduce((a,b)=>distSqXZ(loc,{x:a.x,z:a.z})<distSqXZ(loc,{x:b.x,z:b.z})?a:b);$('#zoneName').textContent=Math.hypot(loc.x,loc.z)<11?'中央部署平台':nearest.name;$('#kills').textContent=state.kills;$('#level').textContent=state.level;$('#coins').textContent=state.coins;$('#charge').textContent=Math.floor(state.charge);$('#heroName').textContent=CHARS[state.char].name;$('#hpText').textContent=`${Math.ceil(state.hero.hp)} / ${Math.ceil(state.hero.maxHp)}`;$('#hpBar').style.width=clamp(state.hero.hp/state.hero.maxHp*100,0,100)+'%';$('#xpText').textContent=`${Math.floor(state.xp)} / ${state.xpNeed}`;$('#xpBar').style.width=clamp(state.xp/state.xpNeed*100,0,100)+'%';const remain=Math.max(0,600-state.time),m=Math.floor(remain/60),ss=Math.floor(remain%60);$('#timer').textContent=state.bossStarted?'OMEGA':`${m}:${String(ss).padStart(2,'0')}`;const sig=JSON.stringify([state.weapons&&Object.entries(state.weapons).map(([id,w])=>[id,w.lv,w.evo]),state.passives]);if(force||state.hudSignature!==sig){state.hudSignature=sig;const d=$('#weaponDock');d.innerHTML='';for(const [id,w] of Object.entries(state.weapons)){const x=document.createElement('div');x.className='slot '+(w.evo?'evo':'');x.title=`${WEAPONS[id].name} · ${w.evo?'进化':`Lv.${w.lv}`}`;x.innerHTML=`<b>${icon(id)}</b><span>${w.evo?'EV':w.lv}</span>`;d.appendChild(x)}for(let i=Object.keys(state.weapons).length;i<5;i++){const x=document.createElement('div');x.className='slot';x.style.opacity='.28';x.innerHTML='<b>＋</b><span>空槽</span>';d.appendChild(x)}$('#passiveDock').innerHTML=Object.entries(state.passives).map(([id,lv])=>`<span title="${PASSIVES[id].name} Lv.${lv}">${icon(id)} <b>${lv}</b></span>`).join('')}$('#shieldText').textContent=state.hero.shield>0?'护盾 '+Math.ceil(state.hero.shield):'装甲完整度';updateCooldowns();updateQuests()}
let toastTimer;function showToast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function endRun(victory=false,quit=false){if(!state.running)return;document.body.classList.remove('playing');$('#pauseBtn').classList.add('hidden');clearInput();state.running=false;state.paused=false;$('#pauseModal').classList.add('hidden');$('#levelModal').classList.add('hidden');meta.runs++;meta.totalKills+=state.kills;const reward=Math.round((state.coins+state.kills*.32+(state.questKills?50:0)+(state.questEvents?50:0)+(state.questEvo?50:0)+(victory?180:0))*DIFFS[state.diff].reward);meta.coins+=reward;if(victory)meta.clears[state.diff]=(meta.clears[state.diff]||0)+1;checkAchievements();saveMeta();const unlocked=[];if(meta.clears.normal>0)unlocked.push('高压难度');if(meta.clears.hard>0)unlocked.push('湮灭难度');$('#resultTitle').textContent=victory?'协议完成':'任务中止';$('#resultSub').textContent=quit?'主动撤离：战场数据已保存。':victory?'OMEGA 核心已摧毁，永久数据已同步。':'机体失效，回收无人机已记录本局数据。';$('#resultStats').innerHTML=`<div><b>${state.kills}</b><span class="tiny">击杀</span></div><div><b>${state.level}</b><span class="tiny">等级</span></div><div><b>${Math.floor(state.time/60)}:${String(Math.floor(state.time%60)).padStart(2,'0')}</b><span class="tiny">生存</span></div><div><b>+${reward}</b><span class="tiny">CR</span></div>`;$('#resultUnlock').textContent=unlocked.length?'解锁进度：'+unlocked.join(' · '):'';const list=$('#achievementList');const lines=[`武器进化：${state.evolutions} 次`,`精英击杀：${state.elitesKilled} 个`,`地图事件：${state.eventCount} 次`,...state.newAchievements.map(x=>'🏆 '+x)];list.innerHTML=lines.map(x=>`<div>${x}</div>`).join('');$('#resultModal').classList.remove('hidden');$('#bossWrap').classList.add('hidden')}

function frame(){requestAnimationFrame(frame);const now=performance.now(),raw=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(state.running&&!state.paused){if(state.victoryAt&&state.time>=state.victoryAt){endRun(true);return}state.time+=raw;updateHero(raw);spawnDirector(raw);weaponTick(raw);updateSkillSequence(raw);updateDefense(raw);updateProjectiles(raw);updateEnemies(raw);if(!state.running)return;updateZones(raw);updateEventZones(raw);updateDrops(raw);if(!state.paused&&state.running)updateFX(raw);updateCompanions(raw);checkAchievements();updateHUD()}renderer.render(scene,camera)}
renderMenu();prepareHangar();frame();

// v4: input lifecycle, built-in test surface, read-only build summaries, and companions.
function clearInput(){for(const k of Object.keys(key))delete key[k];moveTouch.set(0,0);aimTouch.set(0,0);for(const el of document.querySelectorAll('.joy')){el.style.setProperty('--jx','0px');el.style.setProperty('--jy','0px')}}
addEventListener('blur',()=>{clearInput();if(state.running&&!state.paused)togglePause()});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state.running&&!state.paused)togglePause()}});
$('#pauseBtn').onclick=togglePause;
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&state.running)e.preventDefault();if(state.paused&&!$('#levelModal').classList.contains('hidden')&&$('#evolutionModal').classList.contains('hidden')&&['Digit1','Digit2','Digit3'].includes(e.code))$('#choices').children[Number(e.code.slice(-1))-1]?.click()});
$('#skillECard').onclick=useSkill;$('#skillRCard').onclick=useUlt;
$('#skillECard').style.pointerEvents='auto';$('#skillRCard').style.pointerEvents='auto';
for(const el of [$('#skillECard'),$('#skillRCard')]){el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})}
$('#aimJoy').addEventListener('pointerdown',()=>{state.manualAim=true;updateAimLabel()});
$('#hpBar').parentElement.insertAdjacentHTML('afterend','<div id="shieldText">装甲完整度</div>');
function segmentDistanceSq(a,b,p){const x=b.x-a.x,z=b.z-a.z,l=x*x+z*z,t=l?clamp(((p.x-a.x)*x+(p.z-a.z)*z)/l,0,1):0;return(p.x-a.x-x*t)**2+(p.z-a.z-z*t)**2}
function buildInventory(){return `<div>战斗技能 <b>${Object.keys(state.weapons).length}/5</b> · ${Object.entries(state.weapons).map(([id,w])=>`${WEAPONS[id].name} ${w.evo?'EV':w.lv}`).join(' / ')}</div><div>属性模块 <b>${Object.keys(state.passives).length}/6</b> · ${Object.entries(state.passives).map(([id,lv])=>`${PASSIVES[id].name} ${lv}`).join(' / ')||'尚未安装'}</div>`}
function weaponUpgradeText(id,lv){const text={pulse:'伤害提升 · Lv.3 增加弹道',blade:'切割伤害提升 · 高等级增加刃片',mine:'爆破伤害提升 · 增加布雷数量',chain:'伤害提升 · 连锁目标 +1',orbital:'轰击范围提升 · 高等级增加信标',slicer:'切割范围与伤害提升',ember:'灼烧伤害、范围与持续时间提升',sentinel:'伤害提升 · 高等级增加无人机',echo:'伤害提升 · 高等级增加刃轨',field:'辐射范围与伤害提升',vortex:'弹幕数量 +1 · 伤害提升',annihilator:'清扫范围与伤害提升'};return `Lv.${lv+1}/5 · ${text[id]}`}
let companions=[];
function updateCompanions(dt){const w=state.weapons.sentinel,n=w?Math.min(5,1+Math.floor(w.lv/2)+(state.hero.projectiles-1)+(w.evo?2:0)):0;if(companions.length!==n){for(const c of companions)removeObject(c);companions=[];for(let i=0;i<n;i++){const c=actorVisual('drone',0x95bcff,.85,.22,true).root;scene.add(c);companions.push(c)}}for(let i=0;i<n;i++){const angle=state.time*.75+i/n*Math.PI*2;companions[i].position.copy(state.hero.mesh.position).add(new THREE.Vector3(Math.cos(angle)*1.7,1.7+Math.sin(state.time*3+i)*.12,Math.sin(angle)*1.7));companions[i].rotation.y=Math.atan2(state.aim.x,state.aim.z)}}
let audioCtx=null,soundEnabled=true;const audioLast={};
function audioStart(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}}
function audioCue(type){if(!soundEnabled||!audioCtx||audioCtx.state!=='running')return;const now=audioCtx.currentTime,gap={shot:.09,hit:.09,kill:.1,level:.4}[type]||.05;if(now-(audioLast[type]??-1)<gap)return;audioLast[type]=now;const [f,end,duration,vol]=({shot:[620,180,.075,.024],hit:[220,80,.06,.017],kill:[100,28,.2,.045],level:[520,1100,.5,.045],select:[850,1300,.12,.035],dash:[220,950,.22,.04],ult:[100,650,.65,.055],xp:[1000,1500,.065,.012]})[type]||[440,880,.1,.02];const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type==='kill'?'sawtooth':'triangle';osc.frequency.setValueAtTime(f,now);osc.frequency.exponentialRampToValueAtTime(end,now+duration);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(now);osc.stop(now+duration);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
$('#soundBtn').onclick=()=>{soundEnabled=!soundEnabled;$('#soundBtn').textContent='声音 '+(soundEnabled?'开':'关');if(soundEnabled)audioStart()};
$('#skillECard .skillHudName').innerHTML=icon('e')+'棱镜壁垒';$('#skillRCard .skillHudName').innerHTML=icon('r')+'离子超载';
$('#guideBtn').onclick=openGuide;$('#levelGuideBtn').onclick=openGuide;$('#guideClose').onclick=closeGuide;
if(new URLSearchParams(location.search).has('qa'))window.__qa={choiceWeight,evolutionRow,updateDefense,hitHero,bossPattern,bossWarning,openGuide,closeGuide,state,scene,camera,renderer,modelCache,WEAPONS,PASSIVES,CHARS,THREE,startRun,spawnEnemy,damageEnemy,killEnemy,spawnGem,addXp,buildChoices,selectChoice,fireWeapon,useSkill,useUlt,updateDrops,updateFX,updateProjectiles,updateSkillSequence,updateHero,updateEnemies,updateZones,updateCompanions,refreshDerived,updateHUD,togglePause,endRun,actorVisual,removeObject,segmentDistanceSq,telegraphSlam,preloadModels,spawnDirector,weaponTick,world,obstacles,validPos,steerAroundProps};

function bladeVisual(color){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({color,toneMapped:false}),ring=new THREE.Mesh(new THREE.TorusGeometry(.33,.06,5,16,Math.PI*1.6),mat);g.add(ring);const edge=new THREE.Mesh(new THREE.ConeGeometry(.2,.55,3),mat.clone());edge.position.y=.35;g.add(edge);return g}
function lightningArc(a,b,color){let from=a.clone();for(let i=1;i<=5;i++){const to=a.clone().lerp(b,i/5);if(i<5)to.add(new THREE.Vector3(rand(-.3,.3),rand(-.25,.25),rand(-.3,.3)));fxLine(from,to,color,.055);from=to}}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_voidstorm_build',description:'Read current AEGIS-7 health, level and equipped skills.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({running:state.running,paused:state.paused,level:state.level,hp:state.hero?.hp||0,weapons:Object.entries(state.weapons).map(([id,w])=>({name:WEAPONS[id].name,level:w.lv,evolved:w.evo})),passives:state.passives})},{name:'choose_voidstorm_upgrade',description:'Choose one of the three currently displayed upgrade cards and resume play.',inputSchema:{type:'object',properties:{card:{type:'integer',minimum:1,maximum:3}},required:['card'],additionalProperties:false},execute:({card})=>{if(!Number.isInteger(card)||card<1||card>3||$('#levelModal').classList.contains('hidden'))throw new Error('No valid upgrade card is available');$('#choices').children[card-1].click();return{level:state.level,paused:state.paused}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}

function steerAroundProps(pos,dir,rad,id){for(const o of obstacles){const away=pos.clone().sub(o.p).setY(0),distance=away.length(),clearance=o.rad+rad;if(distance>clearance+1.8||distance<.01)continue;away.divideScalar(distance);const toward=dir.dot(away);if(toward>0)continue;const force=(clearance+1.8-distance)/1.8;dir.addScaledVector(away,force*.85);if(toward<-.78){const tangent=new THREE.Vector3(-away.z,0,away.x);dir.addScaledVector(tangent,(id%2?1:-1)*force*.65)}}if(dir.lengthSq()>.001)dir.normalize()}

function weaponMuzzle(actor,dir){const gun=actor.mesh.getObjectByName('rig-rifle');if(gun){actor.mesh.updateMatrixWorld(true);return gun.localToWorld(new THREE.Vector3(0,.015,1.18))}return actor.mesh.position.clone().add(new THREE.Vector3(0,1.45,0)).addScaledVector(dir,.9)}
